### PR TITLE
fix: detached volume reattached after node eviction

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#9781

#### What this PR does / why we need it:

https://github.com/longhorn/longhorn/issues/9781#issuecomment-2475637671

#### Special notes for your reviewer:

`None`

#### Additional documentation or context

`None`

### CODE REVIEW

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1954/

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by c3y1huang** [comment]
@mergify backport v1.7.x

**Comment by c3y1huang** [comment]
@mergify backport v1.6.x

**Pull request merged**
