### PR TITLE
Consider disk space when schedule replica

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/4185

### CODE REVIEW

**Comment by c3y1huang** [comment]
Test result based on https://github.com/longhorn/longhorn-tests/pull/1009 - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1586/

**Review by shuo-wu — COMMENTED** [review]
IMO, it's better to add a setting to enable this feature.
Not sure if some users would prefer to use up some disks first and reserve some big empty disks for large volumes.

**Comment by innobead** [comment]
> IMO, it's better to add a setting to enable this feature. Not sure if some users would prefer to use up some disks first and reserve some big empty disks for large volumes.

Question: how do users possibly prefer using up some disks first if the disk selection is random from disk candidates?

**Review by innobead — APPROVED** [review]

**Comment by shuo-wu** [comment]
Currently, users can achieve that by disabling the scheduling for the reserved disk.
Okey, the same thing can be applied even with this PR merged. We can add the setting later.

**Review by derekbit — APPROVED** [review]
LGTM.
We maybe can provide more strategies (modes), e.g. disk space based, number of replicas (load balance) and etc., for users, and then users can choose the strategy according to their application.

**Comment by iosifnicolae2** [comment]
@c3y1huang in Longhorn v1.4.0 the replicas does not seem to be scheduled on disks with the most usable space.
Eg:
node 1:
  - disk 1 - usable space 1TB out of 4TB
  - disk 2 - usable 1 TB out of 4TB
node 2
  - disk 1 - usable space 1TB out of 4TB
  - disk 2 - usable 1 TB out of 4TB
  - disk 3 - usable 1 TB out of 4TB
  - disk 4 - usable 3 TB out of 4TB
node 3
  - disk 1 - usable space 1TB out of 4TB
  - disk 2 - usable 1 TB out of 4TB
  - disk 3 - usable 1 TB out of 4TB
  - disk 4 - usable 3 TB out of 4TB
 

We have one volume, attached to node 3 with replication factor of 2.
After implementing this issue, the `master` volume should be scheduled on node 3 disk 4, and the replica should be scheduled on node 2 disk 4.

In our case, the replica is scheduled on node 1 disk 2, the node 2 disk 4 remaining unused.

I've tried to manually delete the replica created on node 1 disk 2 but the replica was re-scheduled on the same node and disk.

The algoritmh implemented here should also take into consideration the available disks on another nodes.

**Comment by innobead** [comment]
> @c3y1huang in Longhorn v1.4.0 the replicas does not seem to be scheduled on disks with the most usable space. Eg: node 1:
> 
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
>   node 2
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
> * disk 3 - usable 1 TB out of 4TB
> * disk 4 - usable 3 TB out of 4TB
>   node 3
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
> * disk 3 - usable 1 TB out of 4TB
> * disk 4 - usable 3 TB out of 4TB
> 
> We have one volume, attached to node 3 with replication factor of 2. After implementing this issue, the `master` volume should be scheduled on node 3 disk 4, and the replica should be scheduled on node 2 disk 4.
> 
> In our case, the replica is scheduled on node 1 disk 2, the node 2 disk 4 remaining unused.
> 
> I've tried to manually delete the replica created on node 1 disk 2 but the replica was re-scheduled on the same node and disk.
> 
> The algoritmh implemented here should also take into consideration the available disks on another nodes.

All eligible nodes should be considered as usual, what changes here is to figure out a suitable disk with the most available space for the new replica. Probably need to check why the node has not been selected. 

@iosifnicolae2 Could you help provide the support bundle?

[/scheduler/replica_scheduler.go#L60-L100](https://github.com/longhorn/longhorn-manager/blob/aaa72ad4a60a0e036a21ee1d3ea6e20fa85a1de0/scheduler/replica_scheduler.go#L60-L100)
```go
	// get all hosts
	nodesInfo, err := rcs.getNodeInfo()
	if err != nil {
		return nil, nil, err
	}

	nodeCandidates, multiError := rcs.getNodeCandidates(nodesInfo, replica)
	if len(nodeCandidates) == 0 {
		logrus.Errorf("There's no available node for replica %v, size %v", replica.ObjectMeta.Name, replica.Spec.VolumeSize)
		return nil, multiError, nil
	}

	nodeDisksMap := map[string]map[string]struct{}{}
	for _, node := range nodeCandidates {
		disks := map[string]struct{}{}
		for fsid, diskStatus := range node.Status.DiskStatus {
			diskSpec, exists := node.Spec.Disks[fsid]
			if !exists {
				continue
			}
			if !diskSpec.AllowScheduling || diskSpec.EvictionRequested {
				continue
			}
			if types.GetCondition(diskStatus.Conditions, longhorn.DiskConditionTypeSchedulable).Status != longhorn.ConditionStatusTrue {
				continue
			}
			disks[diskStatus.DiskUUID] = struct{}{}
		}
		nodeDisksMap[node.Name] = disks
	}

	diskCandidates, multiError := rcs.getDiskCandidates(nodeCandidates, nodeDisksMap, replicas, volume, true)

	// there's no disk that fit for current replica
	if len(diskCandidates) == 0 {
		logrus.Errorf("There's no available disk for replica %v, size %v", replica.ObjectMeta.Name, replica.Spec.VolumeSize)
		return nil, multiError, nil
	}

	// schedule replica to disk
	rcs.scheduleReplicaToDisk(replica, diskCandidates)
```

**Comment by iosifnicolae2** [comment]
@innobead done. I've sent the support bundle to longhorn-support-bundle@suse.com from iosif@bringes.io

**Comment by innobead** [comment]
Thanks, @iosifnicolae2 . @c3y1huang will check.

**Comment by iosifnicolae2** [comment]
I've deleted the replica two times from the node under disk pressure and it seems that now was scheduled on another node.

But, as you can see from the support bundle, we have disks which have 90% unused space and dedicated-worker-1 node has only 30% available space.

Also, it might be awesome if we can schedule a cron job for moving replicas as they grow in size on different nodes. In the meantime, we can delete them and they should be recreated on the correct node.

Thank you!

**Comment by c3y1huang** [comment]
> node 1:
> 
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
>   node 2
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
> * disk 3 - usable 1 TB out of 4TB
> * disk 4 - usable 3 TB out of 4TB
>   node 3
> * disk 1 - usable space 1TB out of 4TB
> * disk 2 - usable 1 TB out of 4TB
> * disk 3 - usable 1 TB out of 4TB
> * disk 4 - usable 3 TB out of 4TB

```
dedicated-master-1
- dedicated-master-1-slow-disk-1: ~10Tb (10867756236800b)

dedicated-worker-1
- dedicated-worker-1-fast-disk-1: ~1Tb (1124807475200b)
- dedicated-worker-1-fast-disk-2: ~1Tb (1497995673600b)

dedicated-worker-2
- dedicated-worker-2-fast-disk-1: ~3Tb (3449919897600b)
- dedicated-worker-2-fast-disk-2: ~1Tb (1337668403200b)
- dedicated-worker-2-fast-disk-3: ~1Tb (1202192384000b)
- dedicated-worker-2-fast-disk-4: ~1Tb (1885129932800b)

dedicated-worker-3
- dedicated-worker-3-fast-disk-1: ~1Tb (1849897779200b)
- dedicated-worker-3-fast-disk-2: ~1Tb (1037146521600b)
- dedicated-worker-3-fast-disk-3: ~3Tb (3717516492800b)
- dedicated-worker-3-fast-disk-4: ~1Tb (1554513920000b)
```

> 
> We have one volume, attached to node 3 with replication factor of 2. After implementing this issue, the `master` volume should be scheduled on node 3 disk 4, and the replica should be scheduled on node 2 disk 4.

```
Volume replicas and size on dedicated-worker-3/dedicated-worker-3-fast-disk-3:

- pvc-b52ce958-0ade-4756-8bb3-2bd3bb0b7d87-r-31006b89: ~32Gb (32212254720b)
- pvc-dba6627a-3d04-45f4-a721-89791af6ce8d-r-89215524: ~32Gb (32212254720b)
```

> 
> In our case, the replica is scheduled on node 1 disk 2, the node 2 disk 4 remaining unused.

```
Replica scheduled nodes:

- pvc-b52ce958-0ade-4756-8bb3-2bd3bb0b7d87:
  - dedicated-worker-1: dedicated-worker-1-fast-disk-2
  - dedicated-worker-3: dedicated-worker-3-fast-disk-3
- pvc-dba6627a-3d04-45f4-a721-89791af6ce8d:
  - dedicated-worker-1: dedicated-worker-1-fast-disk-1
  - dedicated-worker-3: dedicated-worker-3-fast-disk-3
```

> 
> I've tried to manually delete the replica created on node 1 disk 2 but the replica was re-scheduled on the same node and disk.

```
> _PVC_="pvc-dba6627a-3d04-45f4-a721-89791af6ce8d"; for name in `k get replica -o wide | grep ${_PVC_} | awk '{print $1}'`; do echo $name: `k get replica/$name -o yaml | grep lastTransitionTime`; done
pvc-dba6627a-3d04-45f4-a721-89791af6ce8d-r-89215524: - lastTransitionTime: "2023-02-08T13:46:29Z"
pvc-dba6627a-3d04-45f4-a721-89791af6ce8d-r-f341e8bd: - lastTransitionTime: "2023-02-02T09:55:46Z"
```

@iosifnicolae2 , can you help to clarify the below:
1. Are you having an issue with `pvc-b52ce958-0ade-4756-8bb3-2bd3bb0b7d87`'s replica `pvc-b52ce958-0ade-4756-8bb3-2bd3bb0b7d87-r-f0507a9c`?
1. The last transition time is `2023-02-02`, is this the last time you've deleted the replica for rescheduling?
1. The manager has been restarted several times, and the log in the support bundle started from `2023-03-07`. If I assumed correctly and the above volume is the one having the issue, there seems to be some outdated information. Are you able to reproduce this issue and send a new support bundle?

**Comment by iosifnicolae2** [comment]
@c3y1huang 
Obs. the example from https://github.com/longhorn/longhorn-manager/pull/1397#issuecomment-1457876424 is not referring to our production cluster

**Answers**
1. No, we had issues with a bigger volume (i think: pvc-85d8f670-2aaf-4714-884c-cb416134f934)
2. I don't know why we don't have logs for this volume, but I think that I deleted the replica from dedicated-worker-1-fast-disk-2 disk  two days ago on 06.03.2023
3. hmm, what does it mean that the instance manager was restarted? unfortunetly, we have this disk configuration only in this production cluster so it's not easy to replicate as the problem was solved by deleting the replica two times because after the first delete, the replica was scheduled on the same disk
   - still, I can't reproduce the issue.. **maybe it was a transient problem**

**Analysis**
  A. _When a new volume is created_, Longhorn should allocate replicas on disk with lower "allocated" space AND lower "used" space.
  - this doesn't seem to happened in our environment because some replicas from `dedicated-worker-2-fast-disk-2` should have been scheduled on `dedicated-worker-2-fast-disk-1`
    image

  B. _At runtime_, the actual used space by volumes can grow unexpectedly (heavy write usage). It would be awesome if replicas are moved automatically on disks with less "used" space. (for now, this is kind of low priority, a temporary workaround would be to _manually move the replica on another disk_)

**The impact of the problem**
1. Some disks will be filled 100% and become unavailable resulting in an OUTAGE.

**Feature requests**
1. When deciding where to schedule a replica, take into consideration both, the "allocated" space and "used" space (solving A case)
    - why taking into consideration only the "used" space is not enough? 
       - because some volumes are used for writing a lot of data (Kafka) and we allocate more space on purpose to reserve more space on disk to accomodate for the high write usage
       - the "used" space is unpredictable because of the high write volumes
2. Allow the option to manually move a replica to another disk (solving B case)


Thank you very much for your support!

**Comment by c3y1huang** [comment]
> 1. No, we had issues with a bigger volume (i think: pvc-85d8f670-2aaf-4714-884c-cb416134f934)

```
# Volume

name: pvc-85d8f670-2aaf-4714-884c-cb416134f934
ownerID: dedicated-worker-2
numberOfReplicas: 2

volumeSize: ~2.6Tb(2684354560000) 

# Replicas scheduled nodes:
- dedicated-worker-2: dedicated-worker-2-fast-disk-2
- dedicated-worker-3: dedicated-worker-3-fast-disk-2
```

Expecting Cluster Nodes' disks availability after deleting replicas.
```
dedicated-master-1
- dedicated-master-1-slow-disk-1: ~10Tb (10867756236800b)

dedicated-worker-1
- dedicated-worker-1-fast-disk-1: ~1Tb (1124807475200b)
- dedicated-worker-1-fast-disk-2: ~1Tb (1497995673600b)

dedicated-worker-2
- dedicated-worker-2-fast-disk-1: ~3Tb (3449919897600b)
- dedicated-worker-2-fast-disk-2: ~4Tb (1337668403200b+2684354560000b = 4022022963200b)
- dedicated-worker-2-fast-disk-3: ~1Tb (1202192384000b)
- dedicated-worker-2-fast-disk-4: ~1Tb (1885129932800b)

dedicated-worker-3
- dedicated-worker-3-fast-disk-1: ~1Tb (1849897779200b)
- dedicated-worker-3-fast-disk-2: ~3.72Tb (1037146521600b+2684354560000b = 3721501081600b)
- dedicated-worker-3-fast-disk-3: ~3.71Tb (3717516492800b)
- dedicated-worker-3-fast-disk-4: ~1Tb (1554513920000b)
```

After freeing the disk space, `dedicated-worker-2/dedicated-worker-2-fast-disk-2`, and `dedicated-worker-3/dedicated-worker-3-fast-disk-2` still have the most available disk size.

> 2. I don't know why we don't have logs for this volume, but I think that I deleted the replica from dedicated-worker-1-fast-disk-2 disk two days ago on 06.03.2023

The support bundle shows the replicas have been on `dedicated-worker-2` and `dedicated-worker-3` since `2023-02-07`.
```
> k get replica | grep ${_PVC_}
pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-e97e7171   running   dedicated-worker-3   dd195a3e-78c9-4cbd-8f52-da8ac9505ec0   instance-manager-r-8089228093fa41a39c54bd4b290924cb   longhornio/longhorn-engine:v1.4.0   29d
pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-ece18305   running   dedicated-worker-2   a3d7ac97-c1da-4ffe-922e-ba007fade9b9   instance-manager-r-8cbb5c75edfb98fc4210971e72f1112c   longhornio/longhorn-engine:v1.4.0   28d

> for name in `k get replica -o wide | grep ${_PVC_} | awk '{print $1}'`; do echo $name: `k get replica/$name -o yaml | grep lastTransitionTime`; done
pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-e97e7171: - lastTransitionTime: "2023-02-07T08:29:10Z"
pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-ece18305: - lastTransitionTime: "2023-02-07T09:59:45Z"
```

However, from the support bundle, it appears to be an additional replica that was created on `2023-03-07` and is unable to be scheduled.
```
pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-ba00a908   stopped 

pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-ba00a908: - lastTransitionTime: "2023-03-07T09:49:25Z"
```

> 3. hmm, what does it mean that the instance manager was restarted?

Maybe this is unrelated but seems there are some restarts for the managers.
```
NAME                                                              READY   STATUS      RESTARTS       AGE
longhorn-manager-2hq8h                                            1/1     Running     4 (34d ago)    56d
longhorn-manager-cj52q                                            1/1     Running     4 (34d ago)    56d
longhorn-manager-gs4gr                                            1/1     Running     6 (29d ago)    56d
longhorn-manager-p6w8r                                            1/1     Running     4 (34d ago)    56d
```

The manager's log seems to start from `2023-03-07`. Not sure if there will be some clues in the previous restarted logs.
```
> k logs longhorn-manager-p6w8r | head -n 1
Defaulted container "longhorn-manager" out of: longhorn-manager, wait-longhorn-admission-webhook (init)
2023-03-07T12:26:43.553147974+01:00 time="2023-03-07T11:26:43Z" level=error msg="There's no available disk for replica pvc-85d8f670-2aaf-4714-884c-cb416134f934-r-ba00a908, size 2684354560000"
```

> Feature requests
> 
> When deciding where to schedule a replica, take into consideration both, the "allocated" space and "used" space (solving A case)
why taking into consideration only the "used" space is not enough?
because some volumes are used for writing a lot of data (Kafka) and we allocate more space on purpose to reserve more space on disk to accomodate for the high write usage
the "used" space is unpredictable because of the high write volumes
> Allow the option to manually move a replica to another disk (solving B case)

Thank you for the input, maybe we can those as the replica scheduler strategies when working on [[FEATURE] The replica scheduler may consider more factors](https://github.com/longhorn/longhorn/issues/5149)

**Pull request merged**
