### PR TITLE
Fix volume cannot be attached when one of the replicas has error IM and the node of IM is still running

### PR DESCRIPTION
**Pull request by PhanLe1010**
The temporary solution is: don't attempt to start replica if the corresponding default IM is `error`, `unknown`, or `stopped`

I think in the long run, we should consider refactor the replica's reconciliation logic in replica controller so that it correctly set the state of the replica

longhorn/longhorn#2475

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Running E2E test

**Review by innobead — APPROVED** [review]
LGTM

@PhanLe1010 could you create a following ticket for the refactoring? then we can do it later.

**Review by shuo-wu — APPROVED** [review]
LGTM as the workaround/hotfix. 

BTW, will the failed replica loop in reusing when the volume is running and the related replica IM cannot be running?

**Comment by PhanLe1010** [comment]
Yes, failed replica will loop in reusing

**Comment by PhanLe1010** [comment]
The E2E core tests passes @innobead

**Pull request merged**
