### PR TITLE
Don't reject the activate command if the restoration is in progress

### PR DESCRIPTION
**Pull request by shuo-wu**
A new field volume.Status.IsStandby is introduced for this feature.

Longhorn #1006

### CODE REVIEW

**Comment by shuo-wu** [comment]
Wait for the manual test passed

**Comment by yasker** [comment]
Just make sure we still able to pull from the backup store one last time before detaching the volume.

**Comment by shuo-wu** [comment]
Manual test, DR volume integration tests and core integration tests passed.

**Comment by yasker** [comment]
https://github.com/longhorn/longhorn/issues/1006

**Pull request merged**
