### PR TITLE
Force disable revision counter for a strict local volume

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#5257

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
Should we take care of the upgrade?

**Comment by derekbit** [comment]
> Should we take care of the upgrade?

It's nice to have. Will update the ticket.

**Review by shuo-wu — APPROVED** [review]

**Comment by innobead** [comment]
@derekbit I think it should be fine to take care of the upgrade path. This only takes effect for new volumes should be OK.

**Comment by derekbit** [comment]
> @derekbit I think it should be fine to take care of the upgrade path. This only takes effect for new volumes should be OK, but need to have a doc if no upgrade path for the migration.

Forgot updating this issue today.
I prefer to handle the upgrade path as well. Will check if there is any potential issue and update the PR.

**Review by innobead — APPROVED** [review]

**Pull request merged**
