### PR TITLE
fix(storage-network): annotated pod in creation loop

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#7640

#### What this PR does / why we need it:

https://github.com/longhorn/longhorn/issues/7640#issuecomment-1888491074

#### Special notes for your reviewer:

`None`

#### Additional documentation or context

`None`

### CODE REVIEW

**Comment by c3y1huang** [comment]
CodeFactor is failing. I don't know why it's checking codes unrelated to this PR.

**Comment by innobead** [comment]
> CodeFactor is failing. I don't know why it's checking codes outside of this PR. cc @innobead

That's OK, but need to see why it verified the non-changed part.

@mantissahz please review this as well.

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@mergify backport v1.6.x

That is a prompt fix @c3y1huang well done.

**Comment by ejweber** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
