### PR TITLE
Set correct sync-agent-port-count when creating a replica process

### PR DESCRIPTION
**Pull request by derekbit**
The default value of sync-agent-port-count is 10 ([code](https://github.com/longhorn/longhorn-engine/blob/master/app/cmd/replica.go#L58)), and it is fine when DefaultReplicaPortCount is 15. Currently, DefaultReplicaPortCount is set to 10, 3 ports are used by replica server, data server and syncagent server. Hence, sync-agent-port-count should be `DefaultReplicaPortCount - 3`.

Longhorn/longhorn#6145

### CODE REVIEW

**Comment by derekbit** [comment]
> sync-agent-port-count should be DefaultReplicaPortCount - 3

Should we use up the remaining port for `sync-agent-port-count`? Any concern?
cc @innobead @shuo-wu

**Comment by derekbit** [comment]
e2e https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4226/

**Comment by shuo-wu** [comment]
> Should we use up the remaining port for sync-agent-port-count? Any concern?

I am fine with using all of the remaining ports.

But should we directly update https://github.com/longhorn/longhorn-engine/blob/0896a6f78315a4fd09e5afa74c85fb3fd5747b56/app/cmd/replica.go#L58 instead?

**Comment by derekbit** [comment]
> > Should we use up the remaining port for sync-agent-port-count? Any concern?
> 
> I am fine with using all of the remaining ports.
> 
> But should we directly update https://github.com/longhorn/longhorn-engine/blob/0896a6f78315a4fd09e5afa74c85fb3fd5747b56/app/cmd/replica.go#L58 instead?

Because default replica port count is set/defined in longhorn-manager, so I changed the value in longhorn-manager. Make them consistent.

**Comment by shuo-wu** [comment]
OK... The default replica port count for spdk engine is defined in `longhorn-spdk-engine`... Do we need to move this default value to `longhorn-engine` then update the default value for this option?

**Comment by derekbit** [comment]
> OK... The default replica port count for spdk engine is defined in `longhorn-spdk-engine`... Do we need to move this default value to `longhorn-engine` then update the default value for this option?

I'm fine with the current implementation. I'm thinking if we can move the port count of spdk volumes to longorn-manager instead.

**Comment by shuo-wu** [comment]
OK. I am OK with either.

**Review by shuo-wu — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
> > OK... The default replica port count for spdk engine is defined in `longhorn-spdk-engine`... Do we need to move this default value to `longhorn-engine` then update the default value for this option?
> 
> I'm fine with the current implementation. I'm thinking if we can move the port count of spdk volumes to longorn-manager instead.

@derekbit Let's create an issue for this improvement.

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Pull request merged**
