### PR TITLE
feat: add updateSnapshotMaxCount and updateSnapshotMaxSize actions

### PR DESCRIPTION
**Pull request by FrankYang0529**
#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/7522

#### What this PR does / why we need it:

add updateSnapshotMaxCount and updateSnapshotMaxSize to Volume actions

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM.

**Review by innobead — CHANGES_REQUESTED** [review]
Didn't find `UpdateSnapshotMaxCountInput` and `UpdateSnapshotMaxSizeInput`? need to create as well.

**Comment by FrankYang0529** [comment]
> Didn't find `UpdateSnapshotMaxCountInput` and `UpdateSnapshotMaxSizeInput`? need to create as well.

We already have it.

https://github.com/longhorn/longhorn-manager/blob/3a118a88d882c90aad784e9e7c85e4530ac96183/api/router.go#L78-L79

**Review by innobead — CHANGES_REQUESTED** [review]
You missed the schema change for `UpdateSnapshotMaxCountInput` and `UpdateSnapshotMaxSizeInput`.

[/api/model.go#L552-L562](https://github.com/longhorn/longhorn-manager/blob/273b6c9261240c89eec6d057fd8611cce7305e04/api/model.go#L552-L562)
```go
func NewSchema() *client.Schemas {
	schemas := &client.Schemas{}

	schemas.AddType("apiVersion", client.Resource{})
	schemas.AddType("schema", client.Schema{})
	schemas.AddType("error", client.ServerApiError{})
	schemas.AddType("attachInput", AttachInput{})
	schemas.AddType("detachInput", DetachInput{})
	schemas.AddType("snapshotInput", SnapshotInput{})
	schemas.AddType("snapshotCRInput", SnapshotCRInput{})
	schemas.AddType("backupTarget", BackupTarget{})
```

**Comment by innobead** [comment]
@FrankYang0529 I think your change should be good enough after checking go-rancher lib. 

The following question in general is why we need to create duplicated input structs that are already generated by go-rancher... This needs to be cleaned up.

[/api/model.go#L551-L590](https://github.com/longhorn/longhorn-manager/blob/273b6c9261240c89eec6d057fd8611cce7305e04/api/model.go#L551-L590)
```go

func NewSchema() *client.Schemas {
	schemas := &client.Schemas{}

	schemas.AddType("apiVersion", client.Resource{})
	schemas.AddType("schema", client.Schema{})
	schemas.AddType("error", client.ServerApiError{})
	schemas.AddType("attachInput", AttachInput{})
	schemas.AddType("detachInput", DetachInput{})
	schemas.AddType("snapshotInput", SnapshotInput{})
	schemas.AddType("snapshotCRInput", SnapshotCRInput{})
	schemas.AddType("backupTarget", BackupTarget{})
	schemas.AddType("backup", Backup{})
	schemas.AddType("backupInput", BackupInput{})
	schemas.AddType("backupStatus", BackupStatus{})
	schemas.AddType("orphan", Orphan{})
	schemas.AddType("restoreStatus", RestoreStatus{})
	schemas.AddType("purgeStatus", PurgeStatus{})
	schemas.AddType("rebuildStatus", RebuildStatus{})
	schemas.AddType("replicaRemoveInput", ReplicaRemoveInput{})
	schemas.AddType("salvageInput", SalvageInput{})
	schemas.AddType("activateInput", ActivateInput{})
	schemas.AddType("expandInput", ExpandInput{})
	schemas.AddType("engineUpgradeInput", EngineUpgradeInput{})
	schemas.AddType("replica", Replica{})
	schemas.AddType("controller", Controller{})
	schemas.AddType("diskUpdate", longhorn.DiskSpec{})
	schemas.AddType("UpdateReplicaCountInput", UpdateReplicaCountInput{})
	schemas.AddType("UpdateReplicaAutoBalanceInput", UpdateReplicaAutoBalanceInput{})
	schemas.AddType("UpdateDataLocalityInput", UpdateDataLocalityInput{})
	schemas.AddType("UpdateAccessModeInput", UpdateAccessModeInput{})
	schemas.AddType("UpdateSnapshotDataIntegrityInput", UpdateSnapshotDataIntegrityInput{})
	schemas.AddType("UpdateOfflineReplicaRebuildingInput", UpdateOfflineReplicaRebuildingInput{})
	schemas.AddType("UpdateBackupCompressionInput", UpdateBackupCompressionMethodInput{})
	schemas.AddType("UpdateUnmapMarkSnapChainRemovedInput", UpdateUnmapMarkSnapChainRemovedInput{})
	schemas.AddType("UpdateReplicaSoftAntiAffinityInput", UpdateReplicaSoftAntiAffinityInput{})
	schemas.AddType("UpdateReplicaZoneSoftAntiAffinityInput", UpdateReplicaZoneSoftAntiAffinityInput{})
	schemas.AddType("UpdateReplicaDiskSoftAntiAffinityInput", UpdateReplicaDiskSoftAntiAffinityInput{})
	schemas.AddType("workloadStatus", longhorn.WorkloadStatus{})
	schemas.AddType("cloneStatus", longhorn.VolumeCloneStatus{})
```

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@FrankYang0529 Please help do a further follow-up about the usage of go-rancher, as I feel we should correct some wrong usage. Also, see if we can do something on that to generate an OpenAPI document, swagger.

**Pull request merged**
