### PR TITLE
NFS endpoint bracketed if ClusterIP is IPv6

### PR DESCRIPTION
**Pull request by chalharu**
Signed-off-by: Mitsuharu Seki <mitsu1986@gmail.com>

### CODE REVIEW

**Comment by innobead** [comment]
@chalharu Thanks for the contribution. Have you verified this? What's your network stack, dual stack? So only changing this will make your RWX volume work correctly in IPv6 env? Because longhorn has not supported IPv6 or dual stack yet, I am quite curious about your setup.

**Comment by chalharu** [comment]
I have verified that the RWX volume works in an IPv6 prefered dual-stack environment by this.
My kube-apiserver is set to --service-cluster-ip-range=[ipv6 range]::/108,10.32.0.0/24.

**Comment by innobead** [comment]
cc @longhorn/qa Can we verify this PR?

**Review by shuo-wu — APPROVED** [review]

**Comment by shuo-wu** [comment]
Not sure if we need to add this to the upgrade path. Probably NO since IPv6 NFS is not supported before this fix.

**Review by innobead — APPROVED** [review]

**Pull request merged**
