### PR TITLE
Allow trimming encrypted devices via UI

### PR DESCRIPTION
**Pull request by shuo-wu**
Users need to enable flag `discards` for the encrypted devices manually first:
https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)

Longhorn/longhorn#836

### CODE REVIEW

**Comment by derekbit** [comment]
Doe encrypted block devices need `--allow-discards` while creating them?

**Comment by shuo-wu** [comment]
> Do encrypted block devices need `--allow-discards` while creating them?

Based on [the doc](https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)) mentioned in [the website PR](https://github.com/longhorn/website/pull/651), there are some security concerns hence device mapper won't enable it by default.

**Comment by derekbit** [comment]
> > Do encrypted block devices need `--allow-discards` while creating them?
> 
> Based on [the doc](https://wiki.archlinux.org/title/Dm-crypt/Specialties#Discard/TRIM_support_for_solid_state_drives_(SSD)) mentioned in [the website PR](https://github.com/longhorn/website/pull/651), there are some security concerns hence device mapper won't enable it by default. Currently, we need to follow the same idea.

Make sense. Should we check if the encrypted device supports trim before executing `nsenter trim...`? Or, will the command `nsenter trim...` return error if `--allow-discard` is set?

**Comment by shuo-wu** [comment]
If the flag is not enabled, `fstrim` will error out. We don't need to complicate this function.

**Review by derekbit — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
