### PR TITLE
Change default setting from ConfigMap to Setting CR

### PR DESCRIPTION
**Pull request by jenting**
#### Proposal Change
Create a new overlay folder to customize the default setting after longhorn manager DaemonSet.
Also, the customize default setting is changed from ConfigMap to Setting CRs.

#### Issue
https://github.com/longhorn/longhorn/issues/2570

### CODE REVIEW

**Review by shuo-wu — CHANGES_REQUESTED** [review]
These codes should be removed as well:
https://github.com/longhorn/longhorn-manager/blob/7bd89abdbae3c406ec56094364cf6c2da1d36d9d/app/daemon.go#L120-L127

Besides, why do you comment the new YAML file in the 2nd commit?

**Comment by jenting** [comment]
> Besides, why do you comment the new YAML file in the 2nd commit?

Well, I'd like to make sure the longhorn-manager DaemonSet deploy first and then the Setting CRs.
However, I realized that the ordering of longhorn-manager DaemonSet and Setting CRs is irrelevant because the longhorn-manager create a new Setting CR with a default value when the Setting CR does not exist.

Drop the 2nd commit.

**Review by shuo-wu — APPROVED** [review]
LGTM. Let's see if the system upgrade via Rancher APP would lead to user-modified setting CRs being overwritten.

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
