### PR TITLE
[BACKPORT v1.4.x] feat(volume): remount volume if it becomes read only

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: https://github.com/longhorn/longhorn/issues/7843

When detecting the filesystem become read only
Try to remount the global mount point to read write again

### CODE REVIEW

**Comment by ChanYiLin** [comment]
ref: https://github.com/longhorn/longhorn/issues/7845

**Comment by ChanYiLin** [comment]
We backport this change to instance-manager v1.4.x
https://github.com/longhorn/longhorn-instance-manager/pull/382#issuecomment-1911186398

but we didn't backport it in manager
https://github.com/longhorn/longhorn-manager/pull/2533

cc @derekbit @innobead

**Comment by innobead** [comment]
@ChanYiLin the PR check failed.

**Comment by innobead** [comment]
Won't fix in 1.4, as it's EOL. If users encounter this issue, suggest them to upgrade to 1.5.x.

**Pull request closed without merging**
