### PR TITLE
feat(support-bundle): pass new parameter SUPPORT_BUNDLE_REQUEST_PURPOSE

### PR DESCRIPTION
**Pull request by weizhe0422**
[Longhorn 5073](https://github.com/longhorn/longhorn/issues/5073)

Signed-off-by: Ray Chang <ray.chang@suse.com>

The [support-bundle-kit PR](https://github.com/rancher/support-bundle-kit/pull/63) will accept this new parameter and execute `collector-longhorn.sh` to collect system information and logs.

### CODE REVIEW

**Review by innobead — COMMENTED** [review]
Why we need this?

**Comment by weizhe0422** [comment]
> Why we need this?

Since the support-bundle-kit can using this parameter to identify and execute the specified collector without impact or overlap exists ones, e.g., harvester.

**Comment by innobead** [comment]
> > Why we need this?
> 
> I think the support-bundle-kit can using this parameter to identify and execute the specified collector without impact or overlap exists ones, e.g., harvester.
> 
> ref. [rancher/support-bundle-kit#63 (comment)](https://github.com/rancher/support-bundle-kit/pull/63#issuecomment-1424085641)

then why need to change the code here? longhorn should be implicit here?

**Comment by weizhe0422** [comment]
I think I can use the namespace where the `support-bundle-manager` resides to identify that the request is coming from the Longhorn system. So I will close this PR.

**Pull request closed without merging**
