### PR TITLE
controller: KubeNodeController stop filtering keys in the enqueue function

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#2100

### CODE REVIEW

**Comment by yasker** [comment]
Is it possible for this PR to disrupt our node failure handling? I am a bit concerned to put it in just before the v1.1.0 release.

**Comment by PhanLe1010** [comment]
LGTM. 
So in this PR, we allow KubeNodeController controller to handle the deletion of Longhorn nodes with different ID. There might be duplicated deletion requests from multiple managers but I don't see a problem.

**Comment by shuo-wu** [comment]
IIRC, duplicate deletion calls won't cause the deletion timestamp update. Hence I think it's fine. And there will be update conflicts still when controllers want to pick up an object containing field`ownerID`. 

Since merging this PR means re-test the node down & deletion case, we can push it to the next release while finding a workaround for now

**Comment by yasker** [comment]
Let's punt it to the next release.

**Review by yasker — APPROVED** [review]

**Pull request merged**
