### PR TITLE
Update backing image manager and bug fix

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#2416

### CODE REVIEW

**Comment by shuo-wu** [comment]
Regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/

**Comment by shuo-wu** [comment]
Since drone won't tag the BIM image like `longhornio/backing-image-manager:20210413` automatically. I just update the tag to `master` for now.

**Comment by innobead** [comment]
> Since drone won't tag the BIM image like `longhornio/backing-image-manager:20210413` automatically. I just update the tag to `master` for now.

@meldafrawi can you help with that? we should release the specific tag instead of master.

**Review by innobead — COMMENTED** [review]
LGTM, except the image tag should be a release version instead master tag as we discussed.

**Comment by shuo-wu** [comment]
The image is updated. Besides, there is a TCP readiness probe introduced for the BIM pods in the last commit.

**Review by innobead — APPROVED** [review]

**Pull request merged**
