### PR TITLE
Fix bug volume cloning feature is broken

### PR DESCRIPTION
**Pull request by PhanLe1010**
The field DataSource should be a string with full information about the source of volume. For example, `snap://vol-name/snapshot-name`

longhorn/longhorn#3508

### CODE REVIEW

**Comment by jenting** [comment]
Looks like the volume cloning feature, it does not follow the type definitions https://github.com/longhorn/longhorn-manager/blob/c72e5b9654fb32541db92eb6e9a171ef19de25ef/k8s/pkg/apis/longhorn/v1beta2/volume.go#L34-L41?

**Comment by PhanLe1010** [comment]
I think it is a typo in `longhorn-manager/k8s/pkg/apis/longhorn/v1beta2/volume.go`, maybe we should change the type `VolumeDataSource` to `VolumeDataSourceType`

There are 4 VolumeDataSourceType but the field volume.Spec.DataSource is intended to have the format `type-prefix://volume-name/snapshot-name`

**Comment by jenting** [comment]
I see, then could you make the change in this PR as well?

**Comment by PhanLe1010** [comment]
Thanks @jenting for helping with the CRDs schema.

I pushed the change

**Review by jenting — APPROVED** [review]
LGTM, thank you.

**Review by innobead — APPROVED** [review]

**Pull request merged**
