### PR TITLE
Notify users about latest stable version of every minor release line

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#3014

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@PhanLe1010 because you introduce a new setting, please also update the manifests and charts of longhorn/longhorn, longhron/longhorn-manager.

**Comment by PhanLe1010** [comment]
@innobead 
This setting is a hidden system setting. I think we don't need to modify any chart similar to the `latest version` setting

**Comment by innobead** [comment]
> @innobead
> This setting is a hidden system setting. I think we don't need to modify any chart similar to the `latest version` setting

Thanks for the clarification!

**Pull request merged**
