### PR TITLE
fix 4302: avoid repeat deletion of pod

### PR DESCRIPTION
**Pull request by w13915984028**
Issue:
https://github.com/longhorn/longhorn/issues/4302

check `pod.DeletionTimestamp` first.

### CODE REVIEW

**Comment by joshimoo** [comment]
hold merge for @PhanLe1010 review

**Comment by PhanLe1010** [comment]
This PR will fix the multiple deletion log messages. It looks good to me

However, the flow will remain the same because multiple deletion requests are collapsed into the first deletion https://github.com/kubernetes/kubernetes/issues/71494. So the behavior when volume crashes will remain the same.

**Review by joshimoo — DISMISSED** [review]
LGTM, as mentioned this only skips the additional delete requests against the API server, even before though sending another delete request against a resource that is in the progress of deletion is a NOOP unless the grace period is set lower i.e. 0

**Review by PhanLe1010 — APPROVED** [review]

**Comment by w13915984028** [comment]
local verification is mentioned in: https://github.com/longhorn/longhorn/issues/4302#issuecomment-1202118521

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@w13915984028 Please help backport to 1.3.x and 1.2.x branches.

**Pull request merged**
