### PR TITLE
Add native rwx support

### PR DESCRIPTION
**Pull request by joshimoo**
Draft PR for preliminary review. 
This is raw and I need to clean this up before final review.
There is also some stuff missing that still needs to be added.

### CODE REVIEW

**Review by yasker — CHANGES_REQUESTED** [review]

**Review by shuo-wu — CHANGES_REQUESTED** [review]
1. The lifecycle of share managers are unclear. When will a share manager get deleted/cleaned up? How do we handle the old share manager when the share manager image is updated?
2. I am confused about the relationship between Longhorn volumes and share managers. It seems that one share managers can handle multiple volumes, which is similar to one instance manager against the related instances. 
3. Can we add unit tests for share-manager-controller

**Review by shuo-wu — CHANGES_REQUESTED** [review]
1. The lifecycle of share managers are unclear. When will a share manager get deleted/cleaned up? How do we handle the old share manager when the share manager image is updated?
2. I am confused about the relationship between Longhorn volumes and share managers. It seems that one share managers can handle multiple volumes, which is similar to one instance manager against the related instances. 
3. Can we add unit tests for share-manager-controller?

**Comment by shuo-wu** [comment]
when there is no workload using a share volume, can this volume get detached? If share volumes cannot be detached, we may need to add some restrictions in volume-controller.

**Comment by joshimoo** [comment]
This is for the multiple volumes per share manager approach which we are currently no longer using, therefore I am closing this for now. Since we will need to refactor this anyway if we decide to continue with this approach.

**Pull request closed without merging**
