### PR TITLE
Don't start migrating when a replica will start to rebuild

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#6961

This addresses a slightly modified version of the original race described in https://github.com/longhorn/longhorn/issues/6961#issuecomment-1854811140.

### CODE REVIEW

**Comment by ejweber** [comment]
1. Deploy a migratable StorageClass.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  migratable: "true"
```

2. Deploy a PVC that uses the migratable storage class.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  storageClassName: test-sc
  resources:
    requests:
      storage: 1Gi
```

3. Deploy a VolumeAttachment that attaches the PVC.

```
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  name: test-va-1
spec:
  attacher: driver.longhorn.io
  nodeName: eweber-v125-worker-e472db53-n8vj8
  source:
    persistentVolumeName: pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
```

4. (The timing can be difficult here. It can take a number of tries to get it right.) Delete a replica of the associated volume. Then, a few seconds later, deploy a VolumeAttachment that attaches the PVC to another node.

```
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
  name: test-va-2
spec:
  attacher: driver.longhorn.io
  nodeName: eweber-v125-worker-e472db53-9kz5b
  source:
    persistentVolumeName: pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
```

Before the fix:

1. The old engine starts to purge snapshots to rebuild the missing replica.
2. The migration starts, so the two RW replicas are cloned.
3. The migration engine becomes ready, allowing the attachment to complete and the workload to start using the migration engine.
4. The old engine starts to rebuild the replacement replica.
8. Longhorn detects a new RO replica and crashes the migration engine.
9. The workload experiences I/O errors.

```
eweber@laptop:~/issue-files/7302> kl get replica --no-headers | head -n 1 | sed 's/ .*//' | xargs kubectl  delete replica -n longhorn-system && sleep 6 && kl apply -f va-2.yaml
replica.longhorn.io "pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-53e87948" deleted
volumeattachment.storage.k8s.io/test-va-2 created

eweber@laptop:~/longhorn-manager> kubetail -n longhorn-system -l app=longhorn-manager | grep -i -e purg -e revert -e match -e "migration engine is ready"
[longhorn-manager-l8cr5] time="2023-12-14T21:23:02Z" level=info msg="Starting snapshot purge before rebuilding, will wait for the purge complete" func="controller.(*EngineController).startRebuilding.func2" file="engine_controller.go:1769" controller=longhorn-engine engine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-0 node=eweber-v125-worker-e472db53-n8vj8 volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:02Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-b08005ca from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-cbd115f7" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:02Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-d4fa36ba from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-cc5cb4fd" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:05Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:10Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:10Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:11Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:12Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:12Z" level=info msg="Starting snapshot purge after rebuilding" func="controller.(*EngineController).startRebuilding.func2" file="engine_controller.go:1883" controller=longhorn-engine engine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-0 node=eweber-v125-worker-e472db53-n8vj8 volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:15Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:16Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-b073d538 from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-38a91cdb" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-l8cr5] time="2023-12-14T21:23:16Z" level=warning msg="The current available migration replicas do not match the record in the migration engine status, will restart the migration engine then update the replica map" func="controller.(*VolumeController).prepareReplicasAndEngineForMigration" file="volume_controller.go:4009" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
```

After the fix:

1. The old engine starts to purge snapshots to rebuild the missing replica.
2. The migration cannot start because there is a replica in the old engines `spec.replicaAddressMap` that doesn't appear in its `status.replicaModeMap`. (Longhorn knows this means rebuilding is about to begin.)
3. The replacement replica rebuilds.
4. The migration starts, so all RW replicas are cloned.
6. No crashes are required.

```
eweber@laptop:~/issue-files/7302> kl get replica --no-headers | head -n 1 | sed 's/ .*//' | xargs kubectl  delete replica -n longhorn-system && sleep 6 && kl apply -f va-2.yaml
replica.longhorn.io "pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-ca2a3c89" deleted
volumeattachment.storage.k8s.io/test-va-2 created

[longhorn-manager-hk8dl] time="2023-12-14T21:20:04Z" level=info msg="Starting snapshot purge before rebuilding, will wait for the purge complete" func="controller.(*EngineController).startRebuilding.func2" file="engine_controller.go:1769" controller=longhorn-engine engine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-0 node=eweber-v125-worker-e472db53-n8vj8 volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:04Z" level=info msg="Need to revert rather than starting migration since the current replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-53e87948 is already in the engine spec, which means it may start rebuilding" func="controller.(*VolumeController).prepareReplicasAndEngineForMigration" file="volume_controller.go:3951" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
...
[longhorn-manager-hk8dl] time="2023-12-14T21:20:18Z" level=info msg="Need to revert rather than starting migration since the current replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-53e87948 is already in the engine spec, which means it may start rebuilding" func="controller.(*VolumeController).prepareReplicasAndEngineForMigration" file="volume_controller.go:3951" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:18Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-6632bea9 from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-53e87948" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:18Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-b9d4f496 from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-cbd115f7" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:18Z" level=info msg="Cloned a new matching replica pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-076a5ec9 from pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-r-cc5cb4fd" func="controller.(*VolumeController).createAndStartMatchingReplicas" file="volume_controller.go:3702" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:22Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:27Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967
[longhorn-manager-hk8dl] time="2023-12-14T21:20:27Z" level=info msg="volume migration engine is ready" func="controller.(*VolumeController).processMigration" file="volume_controller.go:3900" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true migrationEngine=pvc-5701fe8e-0778-4d81-9fc3-d200f5a05967-e-1 migrationNodeID=eweber-v125-worker-e472db53-9kz5b node=eweber-v125-worker-e472db53-n8vj8 owner=eweber-v125-worker-e472db53-n8vj8 shareEndpoint= shareState= state=attached volume=pvc-5701fe8e-0778-4d81-9fc3-d200f5a0596
```

**Review by james-munson — APPROVED** [review]
LGTM

**Comment by james-munson** [comment]
That looks pretty simple.  Thanks for the detailed explanation.  Interesting that in the "after" case, it logged "may start rebuilding" for 15 seconds or so, and then the rebuild took no time to speak of.  I guess it was doing the snapshot purge for that while?

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]

**Comment by ejweber** [comment]
@mergify backport v1.5.x v1.4.x

**Comment by ejweber** [comment]
> That looks pretty simple. Thanks for the detailed explanation. Interesting that in the "after" case, it logged "may start rebuilding" for 15 seconds or so, and then the rebuild took no time to speak of. I guess it was doing the snapshot purge for that while?

We discussed this offline, but for posterity:

We check for the completion of the snapshot purge in intervals of 10 seconds (2 * 5 seconds) before starting the rebuild. In my example above, there is literally no data, so the rebuild is instantaneous. However, we cannot start until we have waited at least 10 seconds for the purge.

https://github.com/longhorn/longhorn-manager/blob/7aa262549f443166d63becf5f8a2ecd351e88c73/controller/engine_controller.go#L1769-L1772

**Pull request merged**
