### PR TITLE
fix(setting): add `applied` field in RESTFul APIs

### PR DESCRIPTION
**Pull request by mantissahz**
#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#8070

### CODE REVIEW

**Review by innobead — DISMISSED** [review]

**Comment by innobead** [comment]
@mantissahz is this missed from the previous PR..?

**Comment by mantissahz** [comment]
>@mantissahz is this missed from the previous PR..?

Yes, it is missed from the previous PR.

**Comment by innobead** [comment]
@mantissahz the PR failed. I didn't dive into it but just restarted it. Please see if anything wrong there if still.

**Comment by mantissahz** [comment]
>@mantissahz the PR failed. I didn't dive into it but just restarted it. Please see if anything wrong there if still.

It might be the name typo in node_controller_test.go ["extra-instance-manger-name"](https://github.com/longhorn/longhorn-manager/blob/c4cd520e9e1845f873b89da3cfb13e4fe94f363f/controller/node_controller_test.go#L1058) and it is different from ["extra-instance-manager-name"](https://github.com/longhorn/longhorn-manager/blob/c4cd520e9e1845f873b89da3cfb13e4fe94f363f/controller/node_controller_test.go#L1086C4-L1086C33)

**Review by innobead — APPROVED** [review]

**Pull request merged**
