### PR TITLE
Fix migration stuck due to snapshot chains in old engine and new engine mismatch

### PR DESCRIPTION
**Pull request by PhanLe1010**
Explanation https://github.com/longhorn/longhorn/issues/6215#issuecomment-1612222566

longhorn/longhorn#6215

### CODE REVIEW

**Comment by PhanLe1010** [comment]
This test passed 10 times after the PR:
```
for i in $(seq 1 20); do echo "Loop iteration: $i"; pytest -svvl test_migration.py::test_migration_with_failed_replica test_migration.py::test_migration_with_unscheduled_replica test_migration.py::test_migration_confirm test_migration.py::test_migration_rollback; done
```

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Review by derekbit — APPROVED** [review]

**Comment by PhanLe1010** [comment]
Cc @mantissahz for reviewing

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Pull request merged**
