### PR TITLE
fix(support-bundle): orphaned ready SupportBundle blocking new creation

### PR DESCRIPTION
**Pull request by c3y1huang**
ref: https://github.com/longhorn/longhorn/issues/5882

### CODE REVIEW

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3826/

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
The current support bundle mechanism can't support concurrent operations like create, download, etc.

@c3y1huang Probably we need to mention this in the doc.

**Comment by innobead** [comment]
@mergify backport v1.4.x

**Pull request merged**
