### PR TITLE
fix(setting): remove offline-replica-rebuilding

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9090

### CODE REVIEW

**Comment by a110605** [comment]
Besides `offline-replica-rebuilding` setting, do we consider remove below fields in `/v1/volumes` API ?
- offlineReplicaRebuiling
- offlineReplicaRebuilingRequired
- updateOfflineReplicRebuilding

Since I'm removing the related UI components in longhorn-ui. ([PR](https://github.com/longhorn/longhorn-ui/pull/780))


Screenshot 2024-07-29 at 11 52 22 AM
Screenshot 2024-07-29 at 11 52 49 AM

**Comment by derekbit** [comment]
> Besides `offline-replica-rebuilding` setting, do we consider remove below fields in `/v1/volumes` API ?
> 
> * offlineReplicaRebuilding
> * offlineReplicaRebuilingRequired
> * updateOfflineReplicRebuilding
> 
> Since I'm removingrelated UI components in longhorn-ui. ([PR](https://github.com/longhorn/longhorn-ui/pull/780))
> 
> Screenshot 2024-07-29 at 11 52 22 AM Screenshot 2024-07-29 at 11 52 49 AM

Removed. @a110605

**Review by c3y1huang — COMMENTED** [review]
Should we also update the generated client apis?

**Comment by derekbit** [comment]
> Should we also update the generated client apis?

Yeah, updated. Thank you.

**Comment by derekbit** [comment]
> 1. Do we still need [UpdateOfflineReplicaRebuilding](https://github.com/derekbit/longhorn-manager/blob/920552e280e2764b00f3feeab50934008556ff24/manager/volume.go#L880)?
> 2. Do we still need the fields in the volume spec and status?

Removed. Thank you.

**Review by c3y1huang — APPROVED** [review]

**Comment by derekbit** [comment]
@mergify backport v1.7.x

**Pull request merged**
