### PR TITLE
upgrade: Check if the label already exists before setting it for a volume

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#3068

### CODE REVIEW

**Comment by shuo-wu** [comment]
@jenting Actually I have a questions here: Will the backup volume label here be removed when the restore/DR volumes are activated? If No, will the label confuse users in the future?

**Comment by jenting** [comment]
> @jenting Actually I have a question here: Will the backup volume label here be removed when the restore/DR volumes are activated? If No, will the label confuse users in the future?

No, I did not remove the label after the restore/DR volume is activated.

I was think that the label was like history to know that this volume was a restore/DR volume.
If we want a state of art, we should remove the label.

**Comment by shuo-wu** [comment]
> If we want a state of art, we should remove the label.

Yeah. It's nice to have. We can consider this later.

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
