### PR TITLE
fix(uninstall): ignore the error 'the object has been modified' when touching backup targets

### PR DESCRIPTION
**Pull request by mantissahz**
#### Which issue(s) this PR fixes:

Issue # longhorn/longhorn#8784

### CODE REVIEW

**Review by ejweber — APPROVED** [review]
LGTM.

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
LGTM

**Comment by mantissahz** [comment]
@Mergifyio backport v1.6.x v1.5x

**Comment by mantissahz** [comment]
@https://github.com/Mergifyio backport v1.5.x

**Pull request merged**
