### PR TITLE
controller: live upgrade should not continue checking the old replica count while the new replicas are activated

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#3052

### CODE REVIEW

**Comment by joshimoo** [comment]
Just checking did you test this with live migration? Since I think it uses the same createMatching function.

**Comment by shuo-wu** [comment]
> Just checking did you test this with live migration? Since I think it uses the same createMatching function.

YES. I just have quick live migration tests for degraded & healthy volumes. It works fine. And just in case, I add an additional check in the migration function.

**Review by innobead — APPROVED** [review]
LGTM

**Review by joshimoo — APPROVED** [review]
LGTM, if I understand correctly it means we cannot do live upgrade / volume migration when a volume is in degraded state.

**Pull request merged**
