### PR TITLE
SPDK volume does not support engine binary client

### PR DESCRIPTION
**Pull request by derekbit**
Longhorn/longhorn#6123

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Comment by shuo-wu** [comment]
Should we allow the UI to list SPDK (rebuilding) snapshot info? If NO, then this simple fix should be enough.

**Comment by derekbit** [comment]
> Should we allow the UI to list SPDK (rebuilding) snapshot info? If NO, then this simple fix should be enough.

I think no. We can support snapshot list when snapshotting is supported.

**Pull request merged**
