### PR TITLE
fix(setting): UI missing asterisk in formulas

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5338

Result:
Screenshot-2023-02-08-16:52:21

### CODE REVIEW

**Review by shuo-wu — APPROVED** [review]

**Review by innobead — COMMENTED** [review]
I think this should be handled by UI part instead to avoid any escaping. 

@smallteeths Could you help with this instead?

**Comment by c3y1huang** [comment]
> I think this should be handled by UI part instead to avoid any escaping.
> 
> @smallteeths Could you help with this instead?

I see. However, this PR also makes the formulas stand out for readability. We can close this PR if it is not helpful. WDYT @innobead ?

**Comment by smallteeths** [comment]
> I think this should be handled by UI part instead to avoid any escaping.
> 
> @smallteeths Could you help with this instead?

ok

**Comment by innobead** [comment]
> > I think this should be handled by UI part instead to avoid any escaping.
> > @smallteeths Could you help with this instead?
> 
> I see. However, this PR also makes the formulas stand out for readability (comparing to the screenshot [here](https://github.com/longhorn/longhorn/issues/5338#issuecomment-1423610792)). We can close this if is not helpful. WDYT @innobead ?

I missed the effect changed by @c3y1huang . @smallteeths to save the efforts, I think this change should be good enough for us, so probably no need to spend time customizing this on UI at the moment. Thanks.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x v1.3.x

**Pull request merged**
