### PR TITLE
Fix bug: we should start conversion webhook before initiating Longhorn datastore

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#8578
More details are at https://github.com/longhorn/longhorn/issues/8578#issuecomment-2121405795

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Putting this PR in draft until doing some more testing and have better code style

**Review by derekbit — COMMENTED** [review]
LGTM

**Comment by PhanLe1010** [comment]
@derekbit Can you review the PR again? It actually still needs a k8s client. Just do not need the Longhorn datastore. 

The new modification will create 2 clients:
1. One without Longhorn datastore
2. One with Longhorn datastore.

I think it should not create a high memory usage issue since the one without Longhorn datastore doesn't have any cache. However, we should still double-check the test  related to multiple clients in Longhorn manager. I forgot the ticket number, do you remember it?

**Comment by derekbit** [comment]
> @derekbit Can you review the PR again? It actually still needs a k8s client. Just do not need the Longhorn datastore.
> 
> The new modification will create 2 clients:
> 
> 1. One without Longhorn datastore
> 2. One with Longhorn datastore.
> 
> I think it should not create a high memory usage issue since the one without Longhorn datastore doesn't have any cache. However, we should still double-check the test related to multiple clients in Longhorn manager. I forgot the ticket number, do you remember it?

longhorn#6866?

**Comment by ChanYiLin** [comment]
LGTM
@PhanLe1010 do you mean this one? https://github.com/longhorn/longhorn/issues/6936

**Comment by PhanLe1010** [comment]
Yes, it is the test plan at https://github.com/longhorn/longhorn/issues/6936#issuecomment-1775396141

Thank you @ChanYiLin and @derekbit !

**Review by derekbit — COMMENTED** [review]
The separate clients LGTM.
I think there is no memory usage issue as @PhanLe1010 said.

**Comment by PhanLe1010** [comment]
Testing looks good. It is ready to be merged after the reviewers approve

**Review by ChanYiLin — DISMISSED** [review]

**Comment by PhanLe1010** [comment]
Looks like there is an new race condition arise after this PR. Please hold on merging

**Comment by innobead** [comment]
@PhanLe1010 is this still draft?

**Comment by PhanLe1010** [comment]
It turned out that we not only have problem with upgrade stuck but also the problem with uninstall stuck because we delete the longhorn-manager daemonset (AKA the conversion webhook server) then list and the the BackupTarget which is still in v1beta1 version. This flow will fail. To solve this problem:
1. A quick hack is https://github.com/longhorn/longhorn-manager/pull/2812/commits/ad321772848e34cc3074af69157bbe1f3eb15260
2. A better solution would be to migrate the API versions for all Longhorn resources in the upgrade path (thus eliminate the need for conversion webhook for future Longhorn upgrade) OR separating the conversion webhook from longhorn-manager 

Due to time pressure, I think we can go with the first approach for now and do the 2nd approach in v1.7.0 . WYDT cc @derekbit @innobead @ChanYiLin @ejweber

**Comment by innobead** [comment]
Sounds good to me.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mergify backport v1.6.x v1.5.x

**Pull request merged**
