### PR TITLE
RWX volume: use bigger timeo, retrans and softerr for nfs client

### PR DESCRIPTION
**Pull request by derekbit**
- biggger timeo and retrans
- softerr: return ETIMEDOUT rather than EIO. Fall back to soft if the option is not supported

Longhorn/longhorn#6655

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM. 

This has a fallback when using softerr, but do we know what versions support softerr?

**Comment by innobead** [comment]
@mergify backport v1.5.x v1.4.x

**Comment by derekbit** [comment]
> This has a fallback when using softerr, but do we know what versions support softerr?

Yes. From [linux kernel 5.2](https://kernelnewbies.org/Linux_5.2).

**Comment by innobead** [comment]
In QA, need to test this fallback.

**Pull request merged**
