### PR TITLE
Fix ineffassign

### PR DESCRIPTION
**Pull request by slayer321**
no issue . related to bugbash

https://lift.sonatype.com/result/longhorn/longhorn-manager/01FHW2JKTWJ3Z4RA5MMT2A53WS?t=CustomTool%20%22golangci-lint%22%7Cineffassign

### CODE REVIEW

**Review by shuo-wu — COMMENTED** [review]
The modifications in the controller test files are duplicates of those in PR https://github.com/longhorn/longhorn-manager/pull/1104.

It's better to wait for the PR merge first.

**Comment by jenting** [comment]
#1104 merged, @slayer321 would you mind keeping work on this PR?

**Comment by slayer321** [comment]
I think closing this PR will be good as all the fix are done in #1104

**Comment by jenting** [comment]
Close this PR since it's be superseded by #1104

**Pull request closed without merging**
