### PR TITLE
Fix don't set volume to faulted if it is attaching the first time and one of the replica failed during attaching process

### PR DESCRIPTION
**Pull request by PhanLe1010**
In this case, there are still other replicas that can be started
so we don't set the volume to faulted here

longhorn/longhorn#4386

### CODE REVIEW

**Review by joshimoo — APPROVED** [review]
LGTM, what state will we be setting the volume to?
- all replicas failed during first attach
- one of the replicas failed during first attach
- no failure during first attach

**Comment by PhanLe1010** [comment]
all replicas failed during first attach -> faulted 
one of the replicas failed during first attach -> attached and healthy
no failure during first attach -> attached and healthy

**Review by innobead — APPROVED** [review]
LGTM

**Review by shuo-wu — APPROVED** [review]

**Comment by innobead** [comment]
@PhanLe1010 Please backport to 1.3 and 1.2.

**Pull request merged**
