### PR TITLE
style(system-restore): job/pod name prefix

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5057

### CODE REVIEW

**Review by derekbit — APPROVED** [review]

**Review by innobead — COMMENTED** [review]
Do we have any resource also have this kind of prefix for name?

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
nit: I feel we should have a factor function in general for creating this kind of prefix name generation for different purposes. Need to review all pod name generation to refactor in total.

**Comment by c3y1huang** [comment]
> nit: I feel we should have a factor function in general for creating this kind of prefix name generation for different purposes. Need to review all pod name generation to refactor in total.

https://github.com/longhorn/longhorn/issues/5060

**Comment by innobead** [comment]
@c3y1huang need to backport to 1.4.x for 1.4.0 release.

**Pull request merged**
