### PR TITLE
fix(webhook): endless secret update retries

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#10054

#### What this PR does / why we need it:

Introduce leader election to sequentially start webhook servers, one node at a time.

#### Special notes for your reviewer:

`None`

#### Additional documentation or context

`None`

### CODE REVIEW

**Comment by c3y1huang** [comment]
@coderabbitai review

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by derekbit** [comment]
@mergify backport v1.8.x

**Comment by derekbit** [comment]
@mergify backport 1.7.x v1.6.x

**Review by ChanYiLin — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
> #### What this PR does / why we need it:
> Introduce leader election to sequentially start webhook servers, one node at a time.

Is there any side effect for this improvement? like pods might be late to start? @c3y1huang

**Comment by innobead** [comment]
Suggest moving the code below to `startWebhooksByLeaderElection` as well, as it is part of webhook initialization. Additionally, pass `clients` to `startWebhooksByLeaderElection` instead of creating a new one in the method. 

[/app/daemon.go#L285-L299](https://github.com/longhorn/longhorn-manager/blob/7114b699543d268b3a42a3529b569284e69eeb14/app/daemon.go#L285-L299)
```go
	clients, err := client.NewClients(kubeconfigPath, true, ctx.Done())
	if err != nil {
		return err
	}

	if err := clients.Datastore.AddLabelToManagerPod(currentNodeID, types.GetAdmissionWebhookLabel()); err != nil {
		return err
	}
	if err := webhook.CheckWebhookServiceAvailability(types.WebhookTypeAdmission); err != nil {
		return err
	}

	if err := recoverybackend.StartRecoveryBackend(clients); err != nil {
		return err
	}

```

**Comment by c3y1huang** [comment]
> Is there any side effect for this improvement? like longhorn-manager app might be late to start? @c3y1huang

The manager will start sequentially, which may impact smaller clusters with slower restarts. However, in my view, this impact is not significant.

**Comment by innobead** [comment]
> > Is there any side effect for this improvement? like longhorn-manager app might be late to start? @c3y1huang
> 
> The manager will start sequentially, which may impact smaller clusters with slower restarts. However, in my view, this impact is not significant.

Sounds good. However, as we use this in nodes running longhorn-manager pods and it differs from traditional Kubernetes control plane usage in terms of scale, see whether this needs any tests in scale if feasible. 

BTW, do we use any lease elsewhere?

**Comment by c3y1huang** [comment]
@mergify backport v1.7.x

**Pull request merged**
