### PR TITLE
controller: Allow DR volume activation if the latest backup is not found

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn 7997

#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/7997

### CODE REVIEW

**Comment by innobead** [comment]
@shuo-wu don't we need to fix this to master, 1.6 as well?

**Comment by shuo-wu** [comment]
Yes. I will create a PR for the master and backport v1.6.x later.

**Comment by shuo-wu** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6370/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6371/

**Comment by shuo-wu** [comment]
The only failed test case `test_migration_with_restore_volume` works fine in my local env...

**Comment by innobead** [comment]
@shuo-wu We need to fix the master and 1.6.

**Pull request merged**
