### PR TITLE
Support s3 pagination

### PR DESCRIPTION
**Pull request by jenting**
#### Proposed Changes
Bump longhorn/backupstore version to support s3 pagination.

#### Linked Issues
https://github.com/longhorn/longhorn/issues/1904

### CODE REVIEW

**Review by yasker — CHANGES_REQUESTED** [review]
Where is the vendor change?

**Comment by jenting** [comment]
> Where is the vendor change?

The longhorn-manager does not have dependency on longhorn/backup store, should we bump the longhorn-manager dependency to make it sure align with longhorn-engine?

**Comment by shuo-wu** [comment]
I think Sheng means that there is no actual dependency file update in the directory `vendor/`. Hence, this PR may be redundant.

**Comment by jenting** [comment]
Close it due to no dependency need to be updated.

**Comment by yasker** [comment]
Sorry for the confusion @jenting @shuo-wu . I didn't realize there is no vendor change needed. In fact, it's still better to have the backupstore dependency updated, to ensure it's on par with the engine.

**Review by yasker — APPROVED** [review]

**Pull request merged**
