### PR TITLE
feat(log): add function name and line number in log message

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: [longhorn/longhorn#5509](https://github.com/longhorn/longhorn/issues/5509)

result:
Screenshot from 2023-10-19 16-12-30

### CODE REVIEW

**Comment by innobead** [comment]
This is good, but having the line number seems a little tedious after reviewing. I think having package and func/method name could be good enough. 

P.S. Having line info is more helpful when hitting a panic and it is already the default behavior in Go, so we don't need to do anything on this.

**Review by innobead — CHANGES_REQUESTED** [review]
For my above comment, WDYT?

**Comment by PhanLe1010** [comment]
I think having line number may be useful in case we have similar logs in the same function. Also, this makes looking up the code more accurately. Kubernetes upstream is also doing this.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Review by shuo-wu — APPROVED** [review]

**Comment by innobead** [comment]
This is helpful info!

> Also, this makes looking up the code more accurately. Kubernetes upstream is also doing this.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Let's backport this.

@mergify backport v1.5.x v1.4.x

**Comment by ChanYiLin** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
