### PR TITLE
 Remove v2 volume offline rebuilding

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#8442

### CODE REVIEW

**Comment by derekbit** [comment]
image

stuck? cc @FrankYang0529

**Comment by innobead** [comment]
> image
> 
> stuck? cc @FrankYang0529

@derekbit branch protection needs to be updated. Derek, please help update each repo after @FrankYang0529 replaces drone with github action. 

image

**Review by innobead — DISMISSED** [review]
LGTM. 

Do we need to remove the setting resource as well? or just leave it as w/o any effect?

**Comment by derekbit** [comment]
> LGTM.
> 
> Do we need to remove the setting resource as well? or just leave it as w/o any effect?

Retaining the setting is fine. Let me add it back.

**Review by innobead — APPROVED** [review]

**Pull request merged**
