### PR TITLE
controller: Fix issue that regular restore volume won't be detached

### PR DESCRIPTION
**Pull request by shuo-wu**
#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/7945

This fixes the regression introduced by https://github.com/longhorn/longhorn-manager/pull/2611

### CODE REVIEW

**Comment by shuo-wu** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6315/

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mergify backport v1.6.x v1.5.x

**Comment by innobead** [comment]
@shuo-wu is it good to merge?

**Comment by shuo-wu** [comment]
I think YES. the only failed test case https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6315/testReport/junit/tests/test_migration/test_migration_with_restore_volume_s3_/ works fine in my local env...

**Pull request merged**
