### PR TITLE
Bump Kubernetes dependency for Longhorn v1.5.0

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#5595

This is a draft to facilitate discussion. I will convert it to an actual PR once the changes I need from https://github.com/longhorn/backing-image-manager/pull/125 are merged.

### CODE REVIEW

**Comment by PhanLe1010** [comment]
The draft PR LGTM

**Comment by PhanLe1010** [comment]
Waiting for e2e core tests' result

**Comment by ejweber** [comment]
> Waiting for e2e core tests' result

This tested fine when I was building it with a local replace for the backing-image-manager change. Testing again with the backing-image-manager from master-head.

- [ ] https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3869/console

**Review by innobead — APPROVED** [review]
LGTM. Will merge after the test is finished and pass.

**Comment by innobead** [comment]
> > Waiting for e2e core tests' result
> 
> This tested fine when I was building it with a local replace for the backing-image-manager change. Testing again with the backing-image-manager from master-head.
> 
> * [ ]  https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3869/console

@ejweber https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3869/testReport/tests/test_basic/test_restore_inc_with_offline_expansion_s3_/ it's not related to backing image, so it could be test flaky.

**Comment by ejweber** [comment]
> @ejweber https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3869/testReport/tests/test_basic/test_restore_inc_with_offline_expansion_s3_/ it's not related to backing image, so it could be test flaky.

Passed in a subsequent run: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3871/testReport/tests/test_basic/.

**Pull request merged**
