### PR TITLE
Clean up e.spec.upgradedReplicaAddressMap when live upgrade is no longer needed

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#6762

### CODE REVIEW

**Comment by PhanLe1010** [comment]
PR is ready for review but need to pass more testing. Please help to review but hold on merging. Thank you

**Review by james-munson — APPROVED** [review]
Seems reasonable.

**Comment by PhanLe1010** [comment]
e2e core test https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5006/

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
