### PR TITLE
fix(metrics): add rwx-volume-fast-failover to upgrade responder colle…

### PR DESCRIPTION
**Pull request by james-munson**
…ction

#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/9347

#### What this PR does / why we need it:

Add setting `rwx-volume-fast-failover` to the list collected for upgrade responder, so we can assess its adoption.

### CODE REVIEW

**Review by ejweber — APPROVED** [review]
LGTM.

As far as I can tell, this is all that is required. Let's wait for @PhanLe1010 to approve as well though, as he is much more of an expert in this area.

**Review by innobead — APPROVED** [review]

**Comment by james-munson** [comment]
@mergify backport v1.7.x

**Comment by PhanLe1010** [comment]
We also need to update this file https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml . Could you please help @james-munson ?

**Comment by james-munson** [comment]
> We also need to update this file https://github.com/longhorn/longhorn/blob/master/deploy/upgrade_responder_server/chart-values.yaml . Could you please help @james-munson ?
In longhorn PR https://github.com/longhorn/longhorn/pull/9376

**Pull request merged**
