### PR TITLE
feat: add DataEngine to generated_instance_manager.go

### PR DESCRIPTION
**Pull request by FrankYang0529**
#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/7095

### CODE REVIEW

**Comment by innobead** [comment]
Is this automatically generated?

**Comment by FrankYang0529** [comment]
> Is this automatically generated?

Yes

**Comment by derekbit** [comment]
Thanks for the fix!

**Review by derekbit — APPROVED** [review]

**Comment by innobead** [comment]
Do we really use the generated code? I doubt now..

**Review by innobead — APPROVED** [review]

**Pull request merged**
