### PR TITLE
Add "Default Data Path" setting

### PR DESCRIPTION
**Pull request by ttpcodes**
This PR adds a new command line flag for the `longhorn-manager` `daemon` called `--default-data-path`, allowing the user to specify which path by default should be used to store the data and replicas created by `longhorn-manager`. This is an optional command line flag, and if not set, will default to the usual path of `/var/lib/rancher/longhorn/` automatically.

Because this would also affect nodes on initial setup of `longhorn-manager`, this setting can only be set via the command line. Additionally, the deployment scripts have been updated with comments indicating what fields in the `spec` a user has to change in order to change the default data path for their `Longhorn` installation.

### CODE REVIEW

**Comment by yasker** [comment]
It's better if we make a global setting instead of a CLI configuration. It will apply to the future nodes and can be carried over upgrade.

**Comment by ttpcodes** [comment]
`default-data-path` seems to properly work on new nodes. Additionally, the CLI flag portion of this PR has been removed, and the "Default Data Path` option will be configurable from inside `longhorn-ui` and only affect newly added nodes instead.

**Comment by yasker** [comment]
Need to update the PR title and commit message as well. Otherwise LGTM.

We need an integration test case for this before we can merge this in.

**Comment by yasker** [comment]
Btw, don't use `close`/`fixes` keywords. Now we need to send the issue to QA after the developer finished development part.

**Comment by ttpcodes** [comment]
The title and commit message have been updated, and the `closes` keyword has been removed from the PR body.

**Comment by yasker** [comment]
LGTM. Waiting for the integration test case.

**Comment by yasker** [comment]
The manual test has been updated at https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan#new-node-with-custom-data-directory

**Pull request merged**
