### PR TITLE
Refactor replica controller for structured log

### PR DESCRIPTION
**Pull request by c3y1huang**
Refactor replica controller to address structured logging implementation.

https://github.com/longhorn/longhorn/issues/1731
https://github.com/longhorn/longhorn-manager/pull/661

### CODE REVIEW

**Comment by yasker** [comment]
@c3y1huang Sorry we missed this one. Can you rebase to the latest code?

@joshimoo can you review when you have time?

**Comment by c3y1huang** [comment]
rebased.

**Comment by yasker** [comment]
cc @joshimoo

**Review by joshimoo — APPROVED** [review]
LGTM, I was concerned about the fact that we already have a node field, 
https://github.com/longhorn/longhorn-manager/blob/ce66fe014abe9a558e5151ca6fd0163b22f09499/app/daemon.go#L130

But thinking some more about this, having the nodeID exposed as what is currently recorded in the relevant resources spec.nodeID seems like a good idea.

**Pull request merged**
