### PR TITLE
ci: copy crds.yaml to longhorn repo

### PR DESCRIPTION
**Pull request by yangchiu**
ci: copy crds.yaml to longhorn repo

For https://github.com/longhorn/longhorn/issues/5854

Signed-off-by: Yang Chiu <yang.chiu@suse.com>

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
In general, LGTM.

However, besides master branch, can we apply this to vx.y.z? can branches support glob pattern like v*.*.*. longhorn/longhorn and longhorn/longhorn-manager have the same branches.

**Comment by yangchiu** [comment]
> In general, LGTM.
> 
> However, besides master branch, can we apply this to vx.y.z? can branches support glob pattern like v*._._. longhorn/longhorn and longhorn/longhorn-manager have the same branches.

I added `v*.*.*` to the trigger of the action, and take the branch name as a parameter instead of hardcoded `master`. This should make it able to open corresponding PRs on `longhorn/longhorn` `v1.3.x` and `v1.4.x` once the backport PRs on `longhorn/longhorn-manager` `v1.3.x` and `v1.4.x` are merged.

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
cc @longhorn/dev

**Pull request merged**
