### PR TITLE
build: reduce iamge size by removing unused packages

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: https://github.com/longhorn/longhorn/issues/5911

### CODE REVIEW

**Review by derekbit — APPROVED** [review]

**Comment by ChanYiLin** [comment]
Wait for e2e test together longhorn-instance-manager/longhorn-engine

**Comment by ChanYiLin** [comment]
e2e tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5257/

**Comment by ChanYiLin** [comment]
e2e tests PASSED

**Review by innobead — APPROVED** [review]

**Comment by mantissahz** [comment]
Hi @ChanYiLin,
Just find that system backup/restore/rollout will use `zip`/`unzip` commands, we might add it back.
cc @c3y1huang

**Comment by innobead** [comment]
@ChanYiLin There are some effects. Need to review if there are some runtime dependencies missing.

**Pull request merged**
