### PR TITLE
Change mutating webhook's failure policy to Fail

### PR DESCRIPTION
**Pull request by derekbit**
Validating webhook's  failure policy is `Fail`. Change mutating webhook's failure policy to `Fail` as well.

https://github.com/longhorn/longhorn/issues/5762

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
It seems the default is fail instead, but why we made that ignore, it didn't make sense.

Good finding @derekbit!

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x v1.3.x

**Comment by derekbit** [comment]
I'm thinking if it is really an issue if using Fail in mutating webhook. If the Longhorn resources runs into issues caused by invalid values in the mutating webhook, stopping and rejecting the resources creation or update looks valid. Isn't it?

**Comment by PhanLe1010** [comment]
> for mutating purpose, will this change impact other pods (example, a pod without PVC) , when the mutating webhook controller pod crashes or network problem, all other pods will be "stopped"

I am not sure why this Longhorn webhook can have affect on the pods don't use Longhorn PVC. These pod should not be affected by this webhook by any means. Could you elaborate more @panpan0000

**Pull request merged**
