### PR TITLE
Don't crash when upgrading volume attachments after a previous failure

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#6653

Problem:

The v1.4.x -> v1.5.0 upgrade logic caches entirely new Longhorn volume attachments. [The v1.5.2 logic that ultimately updates the volume attachments on the cluster](https://github.com/longhorn/longhorn-manager/blob/55a90cf72b98a0399672eb6d1de3fd5e69b98f95/upgrade/util/util.go#L958-L987) assumes that it should do an update to any existing Longhorn volume attachments with the contents of the cached resources. If, for some reason, a previous upgrade v1.4.x -> v1.5.2 failed BUT successfully created Longhorn volume attachments, that logic attempts to do an update with an entirely new Longhorn volume attachment. This is illegal, as `metadata.resourceVersion` is not set.

Solution:

Populate the cache with existing Longhorn volume attachments in the v1.4.x -> v1.5.0 upgrade logic. When we reach the point of actually doing the updates on the cluster, `metadata.resourceVersion` is set.

We do not need to add this fix to master/v1.6.0-dev. That version includes simpler upgrade logic (Longhorn volume attachments already exist during the upgrade and never need to be created).

### CODE REVIEW

**Comment by ejweber** [comment]
v1.5.x upgrades from v1.4.4 are still failing due to https://github.com/longhorn/longhorn/issues/6987. That issue is the cause of the first upgrade failure in v1.5.2-rc1. However, this issue was the direct cause of all subsequent failures. With the fix, logs show that only that issue is blocking upgrade completion.

Every time a longhorn-manager pod obtains leadership NOW:

```
eweber@laptop:~/longhorn> kl get lhva -oyaml
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
  kind: VolumeAttachment
  metadata:
    creationTimestamp: "2023-10-27T14:35:00Z"
    finalizers:
    - longhorn.io
    generation: 1
    labels:
      longhornvolume: pvc-4c988790-5ca1-4369-b8ab-5be0c167151b
    name: pvc-4c988790-5ca1-4369-b8ab-5be0c167151b
    namespace: longhorn-system
    ownerReferences:
    - apiVersion: longhorn.io/v1beta2
      kind: Volume
      name: pvc-4c988790-5ca1-4369-b8ab-5be0c167151b
      uid: f427c926-e96b-49d8-8eed-11a92bb68195
    resourceVersion: "80139613"
    uid: c545b493-6b00-4303-8bde-2b1e2afeab50
  spec:
    attachmentTickets:
      csi-1cc86888d9d3f2cd88a5abd0a0224828dcbefd4abd47c5339da00ca66fbcf4e0:
        generation: 0
        id: csi-1cc86888d9d3f2cd88a5abd0a0224828dcbefd4abd47c5339da00ca66fbcf4e0
        nodeID: eweber-v125-worker-e472db53-9kz5b
        parameters:
          disableFrontend: "false"
        type: csi-attacher
    volume: pvc-4c988790-5ca1-4369-b8ab-5be0c167151b
kind: List
metadata:
  resourceVersion: ""

eweber@laptop:~/longhorn> kl logs longhorn-manager-v6j69
...
time="2023-10-27T16:18:28Z" level=info msg="Start upgrading" func=upgrade.upgrade.func1 file="upgrade.go:129"
time="2023-10-27T16:18:28Z" level=info msg="No API version upgrade is needed" func=upgrade.doAPIVersionUpgrade file="upgrade.go:175"
time="2023-10-27T16:18:28Z" level=info msg="Walking through the resource upgrade path v1.4.x to v1.5.0" func=upgrade.doResourceUpgrade file="upgrade.go:231"
time="2023-10-27T16:18:29Z" level=info msg="Walking through the resource upgrade path v1.5.1 to v1.5.2" func=upgrade.doResourceUpgrade file="upgrade.go:237"
time="2023-10-27T16:18:29Z" level=info msg="Walking through the resource status upgrade path v1.4.x to v1.5.0" func=upgrade.doResourceUpgrade file="upgrade.go:249"
time="2023-10-27T16:18:29Z" level=info msg="Finish upgrading" func=upgrade.upgrade.func1.1 file="upgrade.go:126"
panic: assignment to entry in nil map

goroutine 1742 [running]:
github.com/longhorn/longhorn-manager/upgrade/util.CreateOrUpdateLonghornVersionSetting({0xc00005602e, 0xf}, 0xc00318f650)
        /go/src/github.com/longhorn/longhorn-manager/upgrade/util/util.go:167 +0x1ac
github.com/longhorn/longhorn-manager/upgrade.doResourceUpgrade({0xc00005602e, 0xf}, 0x28266b8?, 0xc00318f650?)
        /go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:262 +0x41b
github.com/longhorn/longhorn-manager/upgrade.upgrade.func1({0x0?, 0x0?})
        /go/src/github.com/longhorn/longhorn-manager/upgrade/upgrade.go:133 +0x13a
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
        /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x105
```

Instead of BEFORE:

```
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
kind: VolumeAttachment
metadata:
  creationTimestamp: "2023-10-27T08:18:30Z"
  finalizers:
  - longhorn.io
  generation: 1
  labels:
    longhornvolume: pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802
  name: pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta2
    kind: Volume
    name: pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802
    uid: db89e6d5-854e-4d1b-9ef8-ba41d4613fc8
  resourceVersion: "3002"
  uid: 5f7a6c31-27ae-4e3c-9797-47398b8f643c
spec:
  attachmentTickets:
    csi-bc2f093b83b08716700629ee0a81e7119b8fe8e43dfaddf8684863d91fc5afca:
      generation: 0
      id: csi-bc2f093b83b08716700629ee0a81e7119b8fe8e43dfaddf8684863d91fc5afca
      nodeID: ip-172-31-34-145
      parameters:
        disableFrontend: "false"
      type: csi-attacher
  volume: pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802
kind: List
metadata:
resourceVersion: ""


root@ip-172-31-47-207:/home/ubuntu# k logs longhorn-manager-b8qmw -n longhorn-system
...
time="2023-10-27T08:35:07Z" level=info msg="Start upgrading" func=upgrade.upgrade.func1 file="upgrade.go:129"
time="2023-10-27T08:35:07Z" level=info msg="No API version upgrade is needed" func=upgrade.doAPIVersionUpgrade file="upgrade.go:175"
time="2023-10-27T08:35:07Z" level=info msg="Walking through the resource upgrade path v1.4.x to v1.5.0" func=upgrade.doResourceUpgrade file="upgrade.go:231"
time="2023-10-27T08:35:07Z" level=info msg="Walking through the resource upgrade path v1.5.1 to v1.5.2" func=upgrade.doResourceUpgrade file="upgrade.go:237"
time="2023-10-27T08:35:07Z" level=debug msg="admit result: UPDATE longhorn.io/v1beta2, Kind=VolumeAttachment longhorn-system/pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802 user=system:serviceaccount:longhorn-system:longhorn-service-account allowed=true err=<nil>" func="webhook.(*Router).admit" file="router.go:89"
time="2023-10-27T08:35:07Z" level=error msg="Upgrade failed: upgrade resources failed: volumeattachments.longhorn.io \"pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" func=upgrade.upgrade.func1.1 file="upgrade.go:124"
time="2023-10-27T08:35:07Z" level=info msg="Upgrade leader lost: ip-172-31-46-9" func=upgrade.upgrade.func2 file="upgrade.go:138"
time="2023-10-27T08:35:07Z" level=fatal msg="Error starting manager: upgrade resources failed: volumeattachments.longhorn.io \"pvc-7a0a31ef-0a34-4ee7-9562-43a7db1e7802\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" func=app.DaemonCmd.func1 file="daemon.go:83"
```

**Comment by ejweber** [comment]
Sorry, renamed branch and accidentally closed this PR. Reopening.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Review by innobead — COMMENTED** [review]
LGTM

**Pull request merged**
