### PR TITLE
Add PriorityClass setting to recurring jobs

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#2444

### CODE REVIEW

**Review by shuo-wu — APPROVED** [review]
LGTM

**Review by shuo-wu — CHANGES_REQUESTED** [review]
Sorry. Longhorn may need to update tolerations or priority classes in the setting controller.

**Comment by PhanLe1010** [comment]
> Sorry. Longhorn may need to update tolerations or priority classes in the setting controller.

Do you mean updating tolerations or priority classes for cronjob? If so, we don't need to do it setting controller because volume controller will update the cronjob when it is not in desired state https://github.com/longhorn/longhorn-manager/blob/1fbd2bf21fdcac5dbc063644c48e66acbdc633d6/controller/volume_controller.go#L2255-L2261

**Comment by shuo-wu** [comment]
> > Sorry. Longhorn may need to update tolerations or priority classes in the setting controller.
> 
> Do you mean updating tolerations or priority classes for cronjob? If so, we don't need to do it setting controller because volume controller will update the cronjob when it is not in desired state
> 
> https://github.com/longhorn/longhorn-manager/blob/1fbd2bf21fdcac5dbc063644c48e66acbdc633d6/controller/volume_controller.go#L2255-L2261

OK. I forgot this part. Then this PR LGTM

**Review by shuo-wu — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Pull request merged**
