### PR TITLE
fix: volume stuck in no backend available leading to IO errors

### PR DESCRIPTION
**Pull request by PhanLe1010**
When replica is restarted unexpectedly, it will get new port number according to our new port allocation logic https://github.com/longhorn/longhorn/issues/8598

Longhorn autosalvage logic is blocked due to replica's port number has changed. Volume controller cannot find matching ip:port in engine's status to mark the replica as failed

This commit will mark all replicas' of the engine as failed if engine.Status.ReplicaModeMap contains all unknown and errored replicas. This trigger the autosalvage flow and unblock the deadlock

See more explaination at https://github.com/longhorn/longhorn/issues/9939#issuecomment-2549996366

longhorn/longhorn#9939

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Ready for review but need some more testing

**Review by james-munson — APPROVED** [review]
That looks reasonable to me.

**Comment by PhanLe1010** [comment]
Testing looks good. PR is ready for review @derekbit

**Comment by PhanLe1010** [comment]
@mergify backport v1.7.x

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by derekbit** [comment]
@mergify backport v1.7.x

**Pull request merged**
