### PR TITLE
WIP: Support IPv6-only clusters

### PR DESCRIPTION
**Pull request by Frankkkkk**
Hi,
This is a WIP MR to support ipv6-only kubernetes clusters.

Cheers

### CODE REVIEW

**Comment by joshimoo** [comment]
Thanks for the PR, I converted it to a draft for the moment.
Please change it back once the PR is ready for review :)

**Comment by yasker** [comment]
@Frankkkkk Hi, just to check if this PR is still up to date? Is there anything we can do to help?

**Comment by Frankkkkk** [comment]
Hi @yasker & @joshimoo ,
Sadly, my priorities have changed as of now :'( I'll try to find a time spot but it's not guaranteed.

PS: I can give you access to a scratch IPv6-only k8s cluster if you desire.

Have a nice week and thanks for the initial help !
Frank

**Comment by yasker** [comment]
@Frankkkkk No worries, we can keep this PR open and feel free to come back to it when you have time.

Also, I don't see anything that might break ipv4 in the PR, so I am OK with merging it if it passed the test. (Of course, you need to convert it to a formal PR and it might need a rebase).

**Pull request closed without merging**
