### PR TITLE
fix(volume-controller): replica CR not created when data-locality set best-effort

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#8869

#### What this PR does / why we need it:

Bypass the precheck when hardNodeAffinity is provided, as users would expect a new Replica CR to be created in this scenario.

#### Special notes for your reviewer:

`None`

#### Additional documentation or context

https://github.com/longhorn/longhorn-manager/pull/2918

### CODE REVIEW

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7094/

**Review by ejweber — COMMENTED** [review]
If I understand correctly, the failure observed in https://github.com/longhorn/longhorn/issues/8869 is caused by:

- We cannot clean up an extra healthy replica automatically until a replica with HardNodeAffinity set to the engine's node exists.
- Since the relevant node is unschedulable, the precheck refuses to allow the creation of this replica.

If I am correct, I have no issues with the implementation. Can you provide a comment with some context here? I think it will be difficult to understand why precheck is disabled for best effort data locality when making changes in the future.

**Comment by c3y1huang** [comment]
> If I understand correctly, the failure observed in [longhorn/longhorn#8869](https://github.com/longhorn/longhorn/issues/8869) is caused by:
> 
> * We cannot clean up an extra healthy replica automatically until a replica with HardNodeAffinity set to the engine's node exists.
> * Since the relevant node is unschedulable, the precheck refuses to allow the creation of this replica.
> 
> If I am correct, I have no issues with the implementation. Can you provide a comment with some context here? I think it will be difficult to understand why precheck is disabled for best effort data locality when making changes in the future.

Yes, you are correct. Also, your comment reminded me that we should probably bypass replica creation when hardNodeAffinity is provided, rather than relying on data-locality best effort.

**Comment by c3y1huang** [comment]
Test WIP: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7108/

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
