### PR TITLE
fix: fix node readiness condition logic

### PR DESCRIPTION
**Pull request by derekbit**
#### Which issue(s) this PR fixes:

Issue Longhorn/longhorn#9616

#### What this PR does / why we need it:

The wrong logic is introduced in the refactor commit https://github.com/longhorn/longhorn-manager/pull/3138

### CODE REVIEW

**Comment by derekbit** [comment]
@mantissahz 
I know you are investigating the issue https://github.com/longhorn/longhorn-manager/pull/3138.  Please help check the PR. If there is anything wrong. Feel free to close this PR and create a new one. Thanks.

**Comment by derekbit** [comment]
- negative test
  - https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1670 passed
  - https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1669 passed
  - regression test (WIP)
    - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7679
    - https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7680

**Comment by c3y1huang** [comment]
Checking to see if this also fixes https://github.com/longhorn/longhorn/issues/9622#issuecomment-2409573002.

**Review by c3y1huang — APPROVED** [review]

**Comment by c3y1huang** [comment]
@mergify backport v1.7.x v1.6.x

**Comment by derekbit** [comment]
@mergify backport v1.7.x v1.6.x

**Pull request merged**
