### PR TITLE
controller: Check backup volume sync time before activation

### PR DESCRIPTION
**Pull request by shuo-wu**
#### Which issue(s) this PR fixes:

Longhorn/longhorn#7946

### CODE REVIEW

**Comment by shuo-wu** [comment]
v1.6.x test:
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6458/
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6459/

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by shuo-wu** [comment]
The failures in the ci regression tests are probably unrelated to this PR. Let's merge this first.

**Comment by shuo-wu** [comment]
@mergify backport v1.5.x v1.6.x

**Pull request merged**
