### PR TITLE
CIFS Backup Store Support

### PR DESCRIPTION
**Pull request by derekbit**
longhorn/longhorn#3599

### CODE REVIEW

**Comment by derekbit** [comment]
Dependencies are updated.

**Comment by innobead** [comment]
@derekbit need to check the PR check failed.

```
# github.com/longhorn/backupstore/util
vendor/github.com/longhorn/backupstore/util/util.go:275:24: mounter.IsMountPoint undefined (type mount.Interface has no field or method IsMountPoint)
```

**Comment by derekbit** [comment]
Dependencies are updated.

**Review by innobead — CHANGES_REQUESTED** [review]
LGTM except one minor comment.

**Review by innobead — APPROVED** [review]

**Pull request merged**
