### PR TITLE
chore: remove Guaranteed Engine/Replica CPU settings

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/5917

### CODE REVIEW

**Comment by c3y1huang** [comment]
Test: WIP

**Comment by c3y1huang** [comment]
Test result:
- full (upgrade): https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3867/
- full: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3868/

**Review by innobead — APPROVED** [review]
LGTM.

**Comment by innobead** [comment]
@longhorn/qa needs to pay more attention on upgrade testing.

**Pull request merged**
