### PR TITLE
[BACKPORT][v1.5.2] Fix backing image manager webhook is never called

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#6328

### CODE REVIEW

**Review by PhanLe1010 — COMMENTED** [review]
NIT: can we add the longhorn issue number to the commit? It make it easier to find the GitHub ticket when looking at the commit history
For example, 

```
Fix backing image manager webhook is never called

longhorn-6328

Signed-off-by: Eric Weber <eric.weber@suse.com>

```

**Comment by PhanLe1010** [comment]
We also need to backport this to 1.4.x and 1.3.x as specified in the issue label

**Comment by ejweber** [comment]
> We also need to backport this to 1.4.x and 1.3.x as specified in the issue label

Will do when this one merges. Since this PR itself is not a backport (I directly branched and cherry-picked a single commit from master), I will want Mergify to backport it. Mergify won't do that until it merges.

**Comment by ejweber** [comment]
@mergify backport v1.4.4

**Comment by ejweber** [comment]
@mergify backport v1.4.x v1.3.x

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Pull request merged**
