### PR TITLE
fix(lint): avoid some lint errors about deprecated fields

### PR DESCRIPTION
**Pull request by james-munson**
#### Which issue(s) this PR fixes:

No tracking issue.

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Looks like it is overlapping with this PR https://github.com/longhorn/longhorn-manager/pull/3060

**Comment by ejweber** [comment]
This one is caused by me.

https://github.com/longhorn/longhorn-manager/pull/3045#issuecomment-2290020232

I chose not to apply this fix because it entirely disables `staticcheck` for these lines instead of just `SA1019`. I thought it would not trigger again if that code wasn't being modified, since we reference the deprecated field in other places in the file. I guess that was incorrect.

**Review by ejweber — APPROVED** [review]
LGTM. Sorry for the inconvenience.

**Comment by ejweber** [comment]
I spoke with @james-munson and @PhanLe1010 offline and we decided to merge this to clean up master in case https://github.com/longhorn/longhorn-manager/pull/3060 doesn't merge for a while.

**Pull request merged**
