### PR TITLE
Fix regressions introduced by migration & rebuilding changes

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#2805
Longhorn/longhorn#2460

### CODE REVIEW

**Comment by shuo-wu** [comment]
regression test: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/458/

**Review by innobead — APPROVED** [review]
LGTM

**Comment by shuo-wu** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/460/

**Comment by shuo-wu** [comment]
I saw Jenting create a ticket for the upgrade regression issue: https://github.com/longhorn/longhorn/issues/3022

**Review by innobead — APPROVED** [review]
LGTM,  we missed `RebuildRetryCount` changed before.

**Review by jenting — APPROVED** [review]
I did an engine upgrade, delete replica, update replica count, and update replica auto-rebalance test, it works well.

**Comment by innobead** [comment]
@shuo-wu Please backport to 1.2.x. Thanks.

**Pull request merged**
