### PR TITLE
Refuse to create an XFS volume smaller than 300 MiB

### PR DESCRIPTION
**Pull request by ejweber**
#### Which issue(s) this PR fixes:

longhorn/longhorn#8488

#### What this PR does / why we need it:

Prevent the creation of Longhorn PersistentVolumes with `fstype: xfs` smaller than `300 MiB`.

### CODE REVIEW

**Comment by ejweber** [comment]
## Before the PR

### Create an XFS PV with a small filesystem using the UI

1. Create a 200 MiB volume in the UI.
2. Use the Create PV/PVC functionality with `File System: XFS` in the UI.
3. There is no creation error.
4. Create a pod that consumes the PVC.

```
apiVersion: v1
kind: Pod
metadata:
  name: test-too-small
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: test-too-small
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test-too-small
      mountPath: /data
  volumes:
  - name: test-too-small
    persistentVolumeClaim:
      claimName: test-too-small
```

5. See mount failures with `kubectl describe test-too-small`.

```
  Warning  FailedMount             0s (x2 over 1s)  kubelet                  MountVolume.MountDevice failed for volume "test-too-small" : rpc error: code = Internal desc = format of disk "/dev/longhorn/test-too-small" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/adb2186f0495712f277ed452e4ccdc61ce885def092e02059606a93459df3699/globalmount") options:("defaults") errcode:(exit status 1) output:(Filesystem must be larger than 300MB.
```

### Create an XFS PC with a small file system using kubectl

1. Create a StorageClass/PVC/Pod that uses a 200 MiB XFS volume.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-too-small
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  fsType: "xfs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-too-small
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: test-too-small
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-too-small
  namespace: default
spec:
  restartPolicy: Always
  containers:
  - name: test-too-small 
    image: alpine:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: test-too-small
      mountPath: /data
  volumes:
  - name: test-too-small
    persistentVolumeClaim:
      claimName: test-too-small

```

2. See mount failures with `kubectl describe test-too-small`.

```
  Warning  FailedMount             2s (x5 over 12s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-2ed690a4-e82c-451f-b9d1-85f6109d108b" : rpc error: code = Internal desc = format of disk "/dev/longhorn/pvc-2ed690a4-e82c-451f-b9d1-85f6109d108b" failed: type:("xfs") target:("/var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/5211b7954bbe197f895895ced365ea02bf667e4710d7c99d73eba147868488e0/globalmount") options:("defaults") errcode:(exit status 1) output:(Filesystem must be larger than 300MB.
```

## After the PR

### Create an XFS PV with a small filesystem using the UI

1. Create a 200 MiB volume in the UI.
2. Use the Create PV/PVC functionality with `File System: XFS` in the UI.
3. See an understandable creation error. (The wording in the screenshot is slightly wrong. See the PR for updated wording.)

image

### Create an XFS PC with a small file system using kubectl

1. Create a StorageClass/PVC/Pod that uses a 200 MiB XFS volume.
2. See PV creation failures with `kubectl describe pvc test-too-small`.

```
  Warning  ProvisioningFailed    1s (x2 over 2s)  driver.longhorn.io_csi-provisioner-57b9f8ff9c-ltmkb_794104e5-79fa-4a7d-869f-567d8173f0b7  failed to provision volume with StorageClass "test-too-small": rpc error: code = Unknown desc = XFS filesystems with size 209715200, smaller than 314572800, are not supported
```

## Snapshots and clones

1. Create an "illegal" StorageClass/PVC/Pod in an old version of Longhorn (use the template from above).
2. Ensure the pod starts running (so an XFS filesystem is definitely created).
3. Create a backup of the PVC using the CSI flow.

```
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snap
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-too-small
spec:
  volumeSnapshotClassName: longhorn-snap
  source:
    persistentVolumeClaimName: test-too-small
```

4. Upgrade to a branch with this PR.
5. Restore the snapshot.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-too-small-restore
  namespace: default
spec:
  storageClassName: test-too-small
  dataSource:
    name: test-too-small
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
```

6. The new logic does not prevent the restore.
7. Clone the PVC.

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-too-small-clone
  namespace: default
spec:
  storageClassName: test-too-small
  dataSource:
    name: test-too-small
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
```

8. The new logic does not prevent the clone.

**Review by derekbit — APPROVED** [review]
LGTM

**Review by derekbit — APPROVED** [review]

**Comment by derekbit** [comment]
@Mergify backport v1.5.x

**Comment by derekbit** [comment]
@mergify backport v1.6.x

**Pull request merged**
