### PR TITLE
ci: change to use GitHub actions

### PR DESCRIPTION
**Pull request by FrankYang0529**
#### Which issue(s) this PR fixes:

https://github.com/longhorn/longhorn/issues/8039

#### What this PR does / why we need it:

Migrate drone to GitHub actions.

### CODE REVIEW

**Comment by FrankYang0529** [comment]
Sample build in my repo: https://github.com/FrankYang0529/longhorn-manager/actions/runs/8797689844

**Comment by FrankYang0529** [comment]
In most of Drone build, the fossa doesn't pass, so I haven't migrated it. I would like to check whether we need it? If not, I will not migrate to GitHub actions.

https://drone-publish.longhorn.io/longhorn/longhorn-manager/2213/1/5

**Review by innobead — APPROVED** [review]
LGTM.

**Comment by innobead** [comment]
> In most of Drone build, the fossa doesn't pass, so I haven't migrated it. I would like to check whether we need it? If not, I will not migrate to GitHub actions.
> 
> [drone-publish.longhorn.io/longhorn/longhorn-manager/2213/1/5](https://drone-publish.longhorn.io/longhorn/longhorn-manager/2213/1/5)

We can skip fossa first, as it's not really actively used now.

**Review by innobead — APPROVED** [review]

**Comment by FrankYang0529** [comment]
@Mergify backport v1.6

**Comment by FrankYang0529** [comment]
@mergify backport v1.6.x

**Comment by FrankYang0529** [comment]
@mergify backport v1.5.x

**Pull request merged**
