### PR TITLE
fix: update engine naming regex to allow non digit enging

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: https://github.com/longhorn/longhorn/issues/9267

Before v1.4.x, users might have engine name like "XXXX-e-12avc" or "XXXX-e-abcd1"
We change to use "-0", "-1" starting from v1.4.4, v1.5.2
https://github.com/longhorn/longhorn-manager/pull/2180

The previous regex didn't allow "XXXX-e-12avc" which  has non digit ending
We should fix it

### CODE REVIEW

**Comment by ChanYiLin** [comment]
Will update the vendor after following PR is merged.
- longhorn-instance-manager: https://github.com/longhorn/longhorn-instance-manager/pull/631

**Comment by derekbit** [comment]
> Will update the vendor after following PR is merged.
> 
> * longhorn-instance-manager: [fix: update engine naming regex to allow non digit enging longhorn-instance-manager#631](https://github.com/longhorn/longhorn-instance-manager/pull/631)

Merged.

**Comment by derekbit** [comment]
@mergify backport v1.7.x

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
