### PR TITLE
Allow kubelet to be down for 10 seconds before responding

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#7302

When kubelet goes down, we generally aren't able to update the node.longhorn.io for 40 seconds.

- https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/pkg/controller/nodelifecycle/config/v1alpha1/defaults.go#L41
- https://github.com/kubernetes/kubernetes/blob/0c645922edcc06adff43c70c02fb56751364bbb5/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L926

However, when kubelet is restarted, it is able to report an interim unhealthy status immediately. In my testing, this interim unhealthy status may only last for less than a second, but it leads directly to the killing of migration engines.

This PR allows us to wait 10 seconds before reacting to an unhealthy kubelet.

### CODE REVIEW

**Comment by ejweber** [comment]
Thanks to @PhanLe1010 and @james-munson for suggesting this fairly straightforward approach. I experimented with more difficult (and potentially more dangerous) approached first.

**Review by james-munson — APPROVED** [review]
Sweet.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Review by c3y1huang — APPROVED** [review]

**Review by innobead — APPROVED** [review]

**Comment by ejweber** [comment]
@mergify backport v1.5.x v1.4.x

**Pull request merged**
