### PR TITLE
controller: Update node when there is a modification

### PR DESCRIPTION
**Pull request by shuo-wu**
This is a straightforward fix without a Github ticket. It's found in PR https://github.com/longhorn/longhorn-manager/pull/1092#discussion_r729693344

### CODE REVIEW

**Comment by shuo-wu** [comment]
The PR is tested by following the instruction https://longhorn.io/docs/1.2.2/advanced-resources/default-disk-and-node-config/#customizing-default-disks-for-new-nodes

**Review by jenting — APPROVED** [review]

**Review by innobead — CHANGES_REQUESTED** [review]
Should we also remove the update code from `syncDefaultNodeTags` as well?

**Comment by shuo-wu** [comment]
> updatedNode, err := knc.ds.UpdateNode(node

Yes. Somehow this modification is not added in the PR... Updated.

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@shuo-wu Please backport to 1.2.x and 1.1.3.

**Pull request merged**
