### PR TITLE
types: Add a new field VIRTUAL_HOSTED_STYLE in backup target credential

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#1552

### CODE REVIEW

**Comment by shuo-wu** [comment]
Right now I prefer to add this config option in the secret. Otherwise, we need to introduce a new setting and update the backup related APIs for this new config, which is unexpected during the release.

**Comment by yasker** [comment]
Hmm? Have we updated the backupstore in the manager?

**Comment by shuo-wu** [comment]
> Hmm? Have we updated the backupstore in the manager?

Updating the manager part is meaningless here since the s3 functions won't be used in this repo.

**Comment by yasker** [comment]
I see what did you mean but it's not the best practice. We don't have a policy to not update backup store if certain conditions met yet. Keep them in sync is easier for code management.

You can update it after RC2, shouldn't be a problem.

**Pull request merged**
